### ISSUE TITLE
Wiki-Seite zu PEPP-PT erweitern

### ISSUE THREAD

**Issue by linuxhelf** [FUB-HCC/20-SWP-CodingOpenness#1]
Kontextualisieren Sie (= Team) die gestellte Zielsetzung. Machen Sie sich mit ihrem Themebereich vertraut und definieren Sie die notwendigen Teilaufgaben. Wichtige Teilaufgaben Nutzen Sie die bereitgestellten Referenzen und Unterlagen. Diskutieren Sie den gewählten technischen Ansatz und beschreiben diesen Ansatz im Detail im Wiki. Erwartetes Ergebnis Sie haben die entsprechende Seiten im Wiki ergänzt um die (1) zugrundliegende Architektur (mit Grafik) (2) den generellen Kommunikationsablauf (UML bietet geeignete Notationsformen).

https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Pan-European-Privacy-Preserving-Proximity-Tracing-%28PEPP-PT%29

**Comment by linuxhelf** [comment]
https://github.com/pepp-pt/pepp-pt-documentation/blob/master/10-data-protection/PEPP-PT-data-protection-information-security-architecture-Germany.pdf

Seite 10 gibt es bereits ein diagram, dieses könnte man übernehmen und vereinfachen

**Comment by linuxhelf** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/1636532/80860244-b89bea00-8c66-11ea-9d0c-f305310e3f70.png)

**Comment by linuxhelf** [comment]
![diagram2](https://user-images.githubusercontent.com/1636532/80861428-cd7c7b80-8c6e-11ea-9222-cc9deae3f7ef.png)

**Comment by linuxhelf** [comment]
hier die Quelldateien zum bearbeiten in drawio
[diagramme.zip](https://github.com/FUB-HCC/20-SWP-CodingOpenness/files/4567481/diagramme.zip)

**Comment by linuxhelf** [comment]
Vorschlag:
- 1. Diagram neuzeichnen, da Text zu klein
- Kritik an Verfahren zusammenfassen und aufschreiben
  Nutzer ist abhängig vom Server (der generiert BluetoothIDs),
  Nutzer der hochlädt, lädt information über andere Nutzer hoch ohne sie zu fragen
- evtl. ein paar allgemeine Sätz
- Dokumentation unvollständig, bei TAN von Gesundheitsamt wiederspruch zu highlevel overview?

**Comment by linuxhelf** [comment]
wir sollten noch bessere Quellen zur Kritik suchen

**Comment by JohBrose** [comment]
Hi ich hab schon mal angefangen das erste diagramm neu zu malen:
![PEPP-PT-1(1)](https://user-images.githubusercontent.com/35258675/81073616-31f63f80-8ee8-11ea-9dc9-7117a51ae29a.png)
[PEPP-PT-1.drawio.zip](https://github.com/FUB-HCC/20-SWP-CodingOpenness/files/4575212/PEPP-PT-1.drawio.zip)

**Comment by linuxhelf** [comment]
ich habe das erste diagram mal etwas überarbeitet und packe es auch gleich ins Wiki
![PEPP-PT-1](https://user-images.githubusercontent.com/1636532/81082154-3116db00-8ef3-11ea-8c49-678c1dee6058.png)
[PEPP-PT-1.zip](https://github.com/FUB-HCC/20-SWP-CodingOpenness/files/4581651/PEPP-PT-1.zip)

**Comment by linuxhelf** [comment]
ich habe das erste diagram mal etwas überarbeitet und packe es auch gleich ins Wiki
Tipp: bei draw.io kann man unter export -> advanced auf 200dpi bessere PNGs erzeugen
![PEPP-PT-1](https://user-images.githubusercontent.com/1636532/81082424-94087200-8ef3-11ea-8dc8-cc556f2705ea.png)
[PEPP-PT-1.zip](https://github.com/FUB-HCC/20-SWP-CodingOpenness/files/4581674/PEPP-PT-1.zip)
