### ISSUE TITLE
Struktur Guideline für die App erstellen - Backendlastig

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#100]
# Bounty
Die App hat einen ziemlich großen Umfang, in dem man sich nicht einfach mit durchlesen zurecht findet, eine Struktur Guideline, die die wichtigsten Files/Packages zu den zentralen Themen (Abgleich der IDs, UI, Rest-Calls, etc.) verdeutlicht, würde helfen
## Scope

- Zu jedem der zentralen Themen sollte ein Hinweis existieren, wo diese zu finden sind
-zentrale Themen sind: ID-Abgleich, Rest-Calls an den Server, lokaler Storage

## Deliverables

-  Wikipage mit Hinweis zu jedem der zentralen Themen, wo diese zu finden sind

## Gain for the project

- Einfacher Einstieg in die Programmierung der App

## Roles

bounty worker: @JohBrose 
bounty reviewer: @dennisn00

**Comment by dennisn00** [comment]
Ich habe es reviewed und Links hinzugefügt. Die wiki Page findet sich [hier](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/CWA-Inhalt---Bakendkommunikation)
