### ISSUE TITLE
Abgleich Strukturgraph - Fragebogen

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#103]
# Bounty
Abgleich Strukturgraph - Fragebogen

Der Fragebogen wurde erweitert, der Strukturgraph müsste also angepasst werden
## Scope

- Strukturgraph erweitern/aktualsieren

## Deliverables

- Strukturgraph

## Gain for the project

- Strukturgraph und Fragebogen sind auf gleichem Stand

## Roles

bounty worker: @username
bounty reviewer: @bernd96 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by linuxhelf** [comment]
habe die Änderungen des Fragebogens einmal grob in den Strukturgraphen überführt, werde aber später noch ein zweites mal durchgehen

**Comment by linuxhelf** [comment]
habe den Strukturgraph nochmal an den Stand des Fragebogens in GoogleDocs angepasst
LimeSurvey hat die selbe Struktur, abgesehen von dem Kapitel "Konkrete Fragen zur Nutzung einer CoronaTracingApp"
hier wurde gestern einiges umgebaut und der Fragebogen muss noch angepasst werden

**Comment by linuxhelf** [comment]
die letzten Änderungen wurden in LimeSurvey und im Strukturgraph eingearbeitet.
Bitte Review machen und dabei die Struktur von allen 3 Sachen (GoogleDocs, Strukturgraph und LimeSurvey vergleichen)

**Comment by bernd96** [comment]
Review durchgeführt, kleinigkeiten(e.g. "weiterführende links" im strukturgraph eingefügt) erledigt.

Außerdem noch die demographischen fragen als optional markiert im strukturgraph, weil momentan "keine antwort" möglich ist.
