### ISSUE TITLE
Konzept Issue Remote Usability

### ISSUE THREAD

**Issue by sontungg** [FUB-HCC/20-SWP-CodingOpenness#105]
Frau Müller-Birn wird uns eine Vorlesung zum Remote Usability Testen senden

## Gain for the project

- Insipiration, Ideen zu Usability gewinnen

**Comment by clmb** [comment]
Die Videos müssen noch auf vrbick geladen werden. 

Die Vorversion des zweiten und dritten Videos können hier geladen werden:
https://we.tl/t-JSwiMFAcbU

Remote Usability Testing ist im dritten Video. Falls Interesse besteht hier der erste Teil der Vorlesung: https://we.tl/t-I4Pe47npic
