### ISSUE TITLE
Struktur Guideline für die App erstellen - Frontendlastig

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#107]
# Bounty

Die App hat einen ziemlich großen Umfang, in dem man sich nicht einfach mit durchlesen zurecht findet, eine Struktur Guideline, die die wichtigsten Files/Packages zu den zentralen Themen (Abgleich der IDs, UI, Rest-Calls, etc.) verdeutlicht, würde helfen

## Scope
- Zu jedem der zentralen Themen sollte ein Hinweis existieren, wo diese zu finden sind
- zentrale Themen sind: UI, Risikoberechnung, Bluetooth, Notifications

## Deliverables

- Wikipage mit Hinweis zu jedem der zentralen Themen, wo diese zu finden sind

## Gain for the project

- Einfacher Einstieg in die Programmierung der App

## Roles

bounty worker: @JuliusBro 
bounty reviewer: @DPHLong

**Comment by DPHLong** [comment]
ist es bereit zu review?

**Comment by JuliusBro** [comment]
noch nicht

**Comment by JuliusBro** [comment]
ready for review, doku liegt [hier](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/CWA-Inhalt-UI,-Bluetooth,-Risikoberechnung,-Notifications)
