### ISSUE TITLE
interactivity: media queries for smaller screens

### ISSUE THREAD

**Issue by omerhod** [FUB-HCC/20-SWP-CodingOpenness#109]
# Bounty
make the website more interactive for smaller screens

## Scope
5-8hr

## Deliverables
code change

## Gain for the project
better UIUX

## Roles

bounty worker: @oussab 
bounty reviewer: @Hod04 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by metaspice** [comment]
First step:

- Will be attempting to implement Bootstrap elements for the website's layout as that does its magic and makes it interactive and mobile ready.
- Work will be under the website/feat/hook_bootstrap
- Progress/Issues will be shared as comments here.
