### ISSUE TITLE
Vergleich der Ansätze - Einheitliche Struktur und Lesbarkeit

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#11]
# Bounty / Aufgabe

Der Wiki-Seite sieht man es meiner Meinung nach sehr an, dass sie von verschiedenn Autoren bearbeitet wurde. Hier wäre die Aufgabe dies zu vereinheitlichen und so die Lesbarkeit zu erhöhen

## Scope / Umfang

- [x] Einheitliches Wording nach der Legende 
- [x] Entfernen der Überflüssigen Tabellenzeilen und Überschriften
- [x] Texte angleichen
- [x] Einheitliche Formatierung

## Deliverables

- Wiki Seite

## Gain for the project / Nutzen für das Projekt

- Einheitlichkeit

## Roles / Rollen

bounty worker: @Erdanf 
bounty reviewer: ....

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Erdnaf** [comment]
Ich hab mich an die Aufgabe gesetzt und das im Branch 'VergleichÜberarbetung' im Wiki festgehalten, kann das jemand reviewen?
(Ich sreibe hier, weil man glaube ich keine PR fürs Wiki erstellen kann, oder?)

**Comment by linuxhelf** [comment]
ich schaus mir gleich mal an

**Comment by linuxhelf** [comment]
sieht schonmal besser aus als vorher, aber da ist noch viel zu machen
ich arbeite gerade mal etwas dran rum, aber nach mir muss nochmal jemand rüberschauen
Ein paar Punkte die noch nicht ganz konsistent sind:
**Begriffe:**
- DP3T, DP 3T oder DP-3T? ich habe erstmal DP3T genommen
- Nutzer, Person, User, Nutzer*innen?
- Client, App, Smartphone?
- Backend, Server?

**Aufbau/Struktur:**
- die vorgeschobenen Blöcke werden unterschiedlich verwendet, ich habe mal probiert es anzugleichen
- Ausführlichkeit/Textlänge: es gibt punkte wohinter 1-2 Sätze stehen, andere haben beim ausklappen gefühlt eine halbe Seite. Das sollte man probieren zu reduzieren
- manche aufgeklappten Abschnitte fangen mit ... an, andere nicht
- bei Architektur ist der Fokus auf zentral/dezentral, hier könnte man es auf 2 Spalten reduzieren, da DCTS/DP3T den gleichen Text haben und dann PEPP-PT,DCTS,DP3T als Beispiele nennen, die man nur in den folgenden Tabellen unterscheidet

**Vorschlag:**
1. Architektur (zentral vs. dezentral)
2. Konkrete Vorschläge/Apps (hier nur auflisten + Zuordnung ob zentral/dezentral + Hintergrund Infos, z.b. Land, Unterstützer)
3. Kommunikation (hier detailliert pro App/Ansatz)
4. Privatsphäre (hier detailliert pro App/Ansatz)

ich gebe dann hier nochmal bescheid, wenn ich mit dem überarbeiten fertig bin und der nächste es sich anschauen kann

**Comment by linuxhelf** [comment]
das "Regenerierung der ID's" bei "Bestätigung der Infizierung" ist noch sehr komisch (der detailtext erklärt was gemeint ist, das sollte man aber besser formulieren)
Benachrichtigung der User*innen finde ich noch unklar was da gemeint ist, hier passt vieles nicht zu einander (wenn man das genauer macht, sollte man auch Push vs Poll anpassen, da es zusammengehört)
Verschlüsselung der Kommunikation ist noch komisch, das sollte man evtl. auftrennen/umbenennen
Interoperabilität genauso
BLE-Nutzung, MAC-Adressen kann man stark kürzen
bei Identität kann man auch nochmal überarbeiten, da einiges doppelt

ich bin damit erstmal durch für heute und würde mich über Feedback (besonders auch zur neuen Struktur/Gruppierung) freuen

**Comment by Erdnaf** [comment]
Habe nochmal bei Architektur in Dezentral/Zentral unterschieden. 
Ansonsten sehr sinvolle Kategorien, ich würde das erstmal so mergen, damit die Experten sich das live anschauen können

**Comment by linuxhelf** [comment]
ok
wenn man oben nur zentral/dezentral schreibt, muss man aber auch bei den Konzepten hinzufügen ob sie zentral oder dezentral sind

**Comment by Erdnaf** [comment]
ah stimmt, das mach ich noch, dann merge ich

**Comment by linuxhelf** [comment]
und die Zeile "zugrundeliegendes Prinzip" bei Architektur kann weg
das dezentral dezentral ist, ist klar :D 
aber ich glaube dann haben wirs

**Comment by Erdnaf** [comment]
hab ich gemacht
