### ISSUE TITLE
Präzisierung Updates

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#112]
# Bounty
Beim Fragebogen sollen die folgenden Angaben in der Tabelle präziser/verständlicher machen
## Scope

-Möglichkeit, manuell über Software-Updates zu entscheiden
-Möglichkeit den Algorithmus zur Risikoabschätzung zu verändern

## Deliverables

-

## Gain for the project

-

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by eagle-seagull** [comment]
Momentan ist die Formulierung so:

Frage: 
"Wie wichtig schätzen Sie die folgenden Funktionen einer Corona Tracing-App ein?"

Antwortmöglichkeit:
"Manuell über Software-Updates entscheiden können (Gefahreneinschätzung manuell aktualisieren, statt automatisch Neue zu erhalten)"

Da die Änderung im Google-Doc schon von einer weiterern Person approved wurde, werde ich dieses Issue damit schließen. Falls die Formulierung noch geändert werden soll, kann es wieder geöffnet oder direkt im Google-Doc angepasst werden.
