### ISSUE TITLE
Testing Team Fragebogen (LimeSurvey)

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#113]
# Bounty

## Scope

- Testlink zur Umfrage anklicken und Umfrage testen
- entweder Feedback (Grammatik, Formulierung, Bugs) direkt in LimeSurvey einarbeiten
- ODER Feedback in Excel eintragen: https://docs.google.com/spreadsheets/d/1DHGd3TdtaSaLkqE9D4wCWrEaouu6tqtj/edit#gid=1252344663

## Deliverables

- Testing der Umfrage

## Gain for the project

- Test-Umfrage für Soziologin Frau Meier, mit so wenig wie möglich Bugs und Typos, fertigstellen

## Roles

bounty worker: @molpremotone
bounty worker: @linuxhelf 
bounty review: @bernd96
bounty review: @eagle-seagull 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by bernd96** [comment]
Ich würd Montag schon testen da ich Dienstag arbeite

**Comment by molpremotone** [comment]
Feedback von mir steht im Excel-Feedback Dokument.

**Comment by bernd96** [comment]
Link an CMB rausgeschickt.
