### ISSUE TITLE
Webseite routing funktioniert nicht immer

### ISSUE THREAD

**Issue by linuxhelf** [FUB-HCC/20-SWP-CodingOpenness#117]
# Bounty
Die Webseite hat jetzt Routing, d.h. jede Unterseite hat einen eigenen link (siehe auch #85 / #95).
Das funktioniert aber nicht immer korrekt.
Manche Seiten sind nicht aufrufbar, die Links erhält man wenn man im Menü auf den eintrag klickt, wenn man aber F5 drückt bekommt man plötzlich einen 404
- https://fub-hcc.github.io/approaches
- https://fub-hcc.github.io/comparison
- https://fub-hcc.github.io/about
- https://fub-hcc.github.io/contact

eigentlich funktioniert nur
https://fub-hcc.github.io/20-SWP-CodingOpenness/

selbst
https://fub-hcc.github.io/
gibt 404, anstatt z.b. auf https://fub-hcc.github.io/20-SWP-CodingOpenness/ weiter zu leiten

Das Zurückgehen im Browser funktioniert, aber nur, wenn man auf einer funktionierenden Seite ist. Von einer 404er ändert sich beim zurückgehen die URL, aber manchmal bleibt 404 stehen, obwohl der Link funktionieren müsste:
Bsp:
1. https://fub-hcc.github.io/20-SWP-CodingOpenness/ öffnen
2. auf z.b. Kontakt klicken
3. F5 klicken -> es steht 404 da
4. in der Browserhistory eins zurück gehen
Nun steht in der URL https://fub-hcc.github.io/20-SWP-CodingOpenness/
aber auf der Seite ist ein 404. Wenn man nochmal F5 drückt, stimmt die seite wieder

- Clicking on one of the links in the home page (out of the 3 Ansätze) moves the page to the "Ansätze" but does not take you directly into the sub-approach.

(ich habe alles in Firefox, Chrome und Edge getestet)
## Scope

- Routing der Webseite überarbeiten

## Deliverables

- Webseite

## Gain for the project

- Lesezeichen funktionieren korrekt

## Roles

bounty worker: @oussab 
bounty reviewer: @Hod04 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [ ] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by metaspice** [comment]
- This issue has been fixed under branch: website/bug/routing.
- Website has been already redeployed with the fix.

----

- Awaiting PR #144 to merge the branch into the website/master branch.
