### ISSUE TITLE
Vergleich der Ansätze - Hinzufügen des Projektes von SAP und Telekom

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#13]
# Bounty / Aufgabe

Das Konzept von SAP und Telekom soll in den Vergleich mit aufgenommen werden

## Scope / Umfang

- Lesen ds Konzeptes auf [Github](https://github.com/corona-warn-app)
- Einfügen der entsprechenden Spalten in die Tabellen

## Deliverables

- Wiki Seite

## Gain for the project / Nutzen für das Projekt

- Vollständigkeit

## Roles / Rollen

bounty worker: ...
bounty reviewer: ...

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by bernd96** [comment]
Interessant sind da auch deren Issues und Userfragen:
https://github.com/corona-warn-app/cwa-documentation/issues?q=is%3Aissue+is%3Aclosed

**Comment by linuxhelf** [comment]
Ich schau mir gleich mal das Konzept an.
Die Frage ist, wie wir damit umgehen wollen. Die 3 vorhandenen Ansätze sind genau das, Ansätze/Konzepte, hier geht es um eine konkrete App.
Wollen wir irgendwann 20Apps/Konzepte gemischt in einer Tabelle?
Ich würde vorschlagen nach Konzepten/Apps zu trennen. Also eine Tabelle die grundlegend unterschiedliche Konzepte/Ansätze vorstellt und eine Tabelle die konkrete Apps darstellt.
Falls also das Konzept der Telekom sehr anders ist als die vorhandenen, würde ich es als neue Spalte machen, ansonsten eher als neue Tabelle, evtl. sogar auf einer extra Seite.

Da es aber die erste App ist, die wir uns anschauen, würde ich es evtl. temporär als Spalte in die aktuelle Tabelle einfügen, bis wir darüber gesprochen haben.

**Comment by linuxhelf** [comment]
Das Github-Repo ist leider noch sehr leer
Abgesehen vom [Scoping Document](https://github.com/corona-warn-app/cwa-documentation/blob/master/scoping_document.md), was mehr eine Zusammenfassung von UserStories ist und den Issues mit Fragen (wie Bernd schon meinte) gibt es nur die Info, dass es von DP3T/TCN inspiriert ist und die Apple/Google-API nutzt.
Mehr Dokumentation/Quellcode soll angeblich in ein paar Tagen kommen, bis dahin würde ich aber vorschlagen probieren wir unseren aktuellen vergleich zu überarbeiten und auf hinzufügen von der Corona Warn App vorzubereiten

**Comment by linuxhelf** [comment]
inzwischen wurde das Github-Repo aktualisiert, und es sind Informationen zur [Architektur](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) vorhanden
Bei kurzem überfliegen sieht es so aus, als ob sie die meisten benötigten Details enthalten, d.h. ein erweitern der Tabelle ist jetzt möglich

**Comment by kraleva** [comment]
> inzwischen wurde das Github-Repo aktualisiert, und es sind Informationen zur [Architektur](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) vorhanden
> Bei kurzem überfliegen sieht es so aus, als ob sie die meisten benötigten Details enthalten, d.h. ein erweitern der Tabelle ist jetzt möglich
Die Anmerkungen von Prof. Wählisch wurden auch entsprechend in Kauf genommen und die Ungenauigkeiten waren korrigiert.

**Comment by linuxhelf** [comment]
ich habe mal auf dem wiki-branch `coronawarnapp` angefangen

**Comment by Erdnaf** [comment]
Hab ein bisschen was hinzugefügt. Ist ja alles sehr detailiert, aber einige Dinge fehlen ja noch von der Doku her

**Comment by linuxhelf** [comment]
ich habe mal den Branch `project-website-vergleich` hinzugefügt
die Markdown-Datei ist unter `project-website/src/Components/Vergleich`
oder auch [hier](https://github.com/FUB-HCC/20-SWP-CodingOpenness/blob/project-website-vergleich/project-website/src/Components/Vergleich/Vergleich-der-Ans%C3%A4tze.md)

**Comment by Erdnaf** [comment]
habe ein paar Dinge hinzugefügt, könnt ihr euch mal anschauen

**Comment by linuxhelf** [comment]
habe auch etwas hinzufügt
Die Webseite wurde jetzt für Markdown umgebaut, ich habe daher unseren Branch entsprechend aktualisiert.
die Datei wurde verschoben, sie ist jetzt im Ordner
`project-website/src/Markdown/`
bzw. [hier](https://github.com/FUB-HCC/20-SWP-CodingOpenness/blob/project-website-vergleich/project-website/src/Markdown/Vergleich.md)

**Comment by Erdnaf** [comment]
Hab noch eine Kleinigkeit geändert, aber ansonsten können wir denke ich einen Pull request erstellen.
(@linuxhelf kannst du das machen? ich hab wenig Erfahrung und Angst, dass ich was falsch mache ;-))

**Comment by linuxhelf** [comment]
ich kanns gerne probieren 😁
so, #49 ist erstellt

**Comment by kraleva** [comment]
Dankeschön, dass ihr das Pull-Request gemacht habt, ich werde es sicherlich verkacken. Ich hab auch am Samstag einige Dinge hinzugefügt. Ich bin auch damit einverstanden, dass es soweit fast fertig aussieht, einige Informationen fehlen dennoch noch in der offiziellen Dokumentation, deswegen wäre es nicht momentan möglich alles auszufüllen.
