### ISSUE TITLE
Erstellung eines Beispiel-Screens zur Erweiterung der App

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#130]
# Bounty
Zum Erproben der Technologien soll eine Art Dummy-Screen erstellt werden, den wir selber in die App einfügen.
## Scope

- einmal das offizielle CWA projekt forken
- einen Screen und eine Überleitung in diesen erstellen
- der Screen soll sich an die Design Guidelines halten
- der Screen soll irgendeine Form von input beinhalten, der auch abgespeichert wird

## Deliverables

- erweiterter Code der App, sollte auch im Emulator abspielbar sein

## Gain for the project

- grundlegendes Codeverständnis

## Roles

bounty worker: @dennisn00 
bounty reviewer: @JuliusBro

**Comment by dennisn00** [comment]
@JohBrose und ich haben einen Test Screen hinzugefügt. Eine kurze Dokumenation findet sich hier: https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Erstellen-eines-weiteren-Screens und den gesamten Code hier: https://github.com/dennisn00/Corona-Warn-App
@JuliusBro bitte reviewen!
