### ISSUE TITLE
Long Dang muss App installieren

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#137]
# Bounty
App installieren
## Scope

- App installieren

## Deliverables

- installierte App, Fähigkeit, ein Video davon zu machen

## Gain for the project

- Wissen, wie man die App installiert und zum laufen bekommt

## Roles

bounty worker: @DPHLong 
bounty reviewer: @DPHLong

**Comment by DPHLong** [comment]
Ich habe den App installiert und eine kleine Video aufgenommen.

**Comment by DPHLong** [comment]
Links von Video:
https://drive.google.com/file/d/16GS-_BI_l9rXBhvnHpNIAMEEvn1KwgEX/view?usp=sharing
