### ISSUE TITLE
Fragebogen - Auswahl des Werkzeugs + Einrichtung

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#14]
# Bounty / Aufgabe
Auswählen und Einrichten eines Werkzeugs zur Erstellung der Umfragen

## Scope / Umfang
- Evaluieren vorhandener Tools
- Beschaffen von Lizenzen o.ä.

## Deliverables

- Werkzeug + evtl. Tutorial

## Gain for the project / Nutzen für das Projekt

- Wir können unsere Fragen in einen Online Fragebogen packen
- Fragebogen ist beantwortbar.

## Roles / Rollen

bounty worker/reviewer: @eagle-seagull 
bounty reviewer/worker: @julizet 

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by julizet** [comment]
Entscheidung für Tool "LimeSurvey", weil Installation und Konfiguration ad hoc möglich
Ggf. Votingo zusätzlich nutzen, sobald Rückmeldung von Support erhalten.

**Next Step:**
* Konfiguration LimeSurvey unter Nutzung von MySQL Datenbank & Server der FUB

**Comment by julizet** [comment]
### How to config LimeSurvey
**Download:** 
https://www.limesurvey.org/stable-release

**Einrichtung DB Guide:** 
https://www.zedat.fu-berlin.de/tip4u_61.pdf

**DB verwalten:** 
https://userpage.fu-berlin.de/db-admin/

**Finally Guide:**
https://userpage.fu-berlin.de/~rober/blog/2016/02/limesurvey-install-userpage/

**Comment by julizet** [comment]
LimeSurvey ist eingerichtet
