### ISSUE TITLE
Weiterführende Links einfügen

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#140]
# Bounty
Weiterführende Links sammeln und in Limesurvey eintragen (Frage 11 im Feedback)

## Scope

-

## Deliverables

-

## Gain for the project

-

## Roles

bounty worker: @bernd96 
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Erdnaf** [comment]
Werden in Limesurvey beim Abschluss der Umfrage angezeigt

**Comment by linuxhelf** [comment]
wir haben uns entschlossen die Links hinter den Fragebogen zu schieben, damit man nicht vom Fragebogen abgelenkt wird.
Sie erscheinen dann, wenn man den Fragebogen abgesendet hat

**Comment by bernd96** [comment]
Das gefällt mir. Ich habe noch einen Link zum Coronavirus allgemein hinzugefügt und den Strukturgraph ergänzt. Review ist freigegeben.

**Comment by Erdnaf** [comment]
Hab noch ein Sonderzeichen entfernt, aber passt ansonsten

**Comment by eagle-seagull** [comment]
Momentan sind die weiterführenden Links unter "Text elements > End message" eingefügt und so formuliert:

> Vielen Dank für Ihre Teilnahme!
> 
> Hier finden Sie weiterführende Informationen zu unserem Projekt und über die COVID-19 APP:
>
>Informationen der Bundeszentrale für gesundheitliche Aufklärung zu COVID-19: https://www.infektionsschutz.de/coronavirus/Informationen
über unser Projekt: https://fub-hcc.github.io/20-SWP-CodingOpenness/Informationen
über die COVID-19 App: https://www.coronawarn.app/de/

Ich habe noch einen Zeilenumbruch nach "APP:" eingefügt.

Vorher war ein Platzhalter "Hier Links einfügen:" für weiterführende Links bei der Frage "Was würde Sie an der Benutzung einer App mit den oben genannten Eigenschaften hindern?" vorhanden. Diesen sehe ich nicht mehr und gehe davon aus, dass dieser entfernt wurde.


Ich werde dieses Issue hiermit schließen.
