### ISSUE TITLE
neue Corona-Tracing App im Mittelpunkt

### ISSUE THREAD

**Issue by tratond01** [FUB-HCC/20-SWP-CodingOpenness#147]
Die Seite sollte nun umstruktuiert werden. Die neue Corona-Tracing App sollte nun im Mittelpunkt stehen. Damit sollte alles von der App ausgehen gedacht werden. Der Vergleich der Ansätze ist gut und wichtig, wenn klar wird, wie die neue App im Vergleich zu den anderen Ansätzen funktioniert. Gibt es dafür bereits Angaben?

**Comment by omerhod** [comment]
- emphasize our contribution rather than analyzing the approaches.
- add additional information that isn't mentioned in the official documentation. 
- coordinate with Orga-team for information, activities, etc.
