### ISSUE TITLE
Gekürzte Variante

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#149]
# Bounty / Aufgabe

Die Datenschutzerklärung ist wie jede Datenschutzerklärung lang.
Es wäre schön, wenn es auch eine kurze/übersichtliche Variante gibt.

## Scope / Umfang

- Paper lesen (siehe Link unten)
- Erkenntnisse mit Datenschutzerklärung der Corona-App abgleichen
- konkrete Verbesserungsvorschläge liefern

## Deliverables

- einfache / gekürzte Variante liefern

## Gain for the project / Nutzen für das Projekt

- fachliche Richtigkeit
- Datenschutz-Thema für nicht "Techies" zugänglich machen

## Roles / Rollen

bounty worker: @julizet 
bounty reviewer: @Erdanf @linuxhelf 

Hierzu ist folgendes zu klären:

- [ ] Wie ist es rechtlich? darf man zusätzlich ein kurze Variante angeben
- [ ] Gibt es bereits Firmen die sowas haben? Vielleicht zum Vergleich anschauen
- [ ] Nachfragen ob sie soetwas überhaupt haben wollen oder sowieso nein sagen
- [ ] probieren eine kurze Version zu schreiben
- [ ] darüber nachdenken wie man es in die App integrieren kann (Toggle zum umschalten auf der Ansicht?)

**Comment by Erdnaf** [comment]
https://petsymposium.org/2020/files/papers/issue2/popets-2020-0037.pdf
darin die Quellen 8-10

**Comment by julizet** [comment]
Kann diese Quelle noch empfehlen (IEEE):

_Ghazinour, K. and Albalawi, T., 2016, August. A usability study on the privacy policy visualization model. In 2016 IEEE 14th Intl Conf on Dependable, Autonomic and Secure Computing, 14th Intl Conf on Pervasive Intelligence and Computing, 2nd Intl Conf on Big Data Intelligence and Computing and Cyber Science and Technology Congress (DASC/PiCom/DataCom/CyberSciTech) (pp. 578-585). IEEE._

**Key Outcome:** **The PPVM successfully faded out all usability problems related to notice/awareness. The model symbols of the privacy policy simplified users’
understanding; the variety and the order of symbols give users
a holistic view of the privacy policy.**

Und diese ([Open Source Link](https://www.emerald.com/insight/content/doi/10.1108/09685221211219155/full/html?casa_token=-yqn0Wj8w2wAAAAA:gj8sWdbJqaMdmvF2l96g6LeZGQue58yD505J3wWyuwQY2v_RpVqLnPBMJfAZ_xyiGoGTwrKivhjOWZKzUnqIOfQ3Ja-3CSXrXPSDgAR2yERiKDaV3kE)):

Clarke, N., Furnell, S., Angulo, J., Fischer‐Hübner, S., Wästlund, E. and Pulls, T., 2012. Towards usable privacy policy display and management. Information Management & Computer Security.

**Key Outcome:** **Showing privacy mismatches inside a two-dimensional table was
preferred by users in general.**

**Comment by julizet** [comment]
- if too long --> bouncing rate is high
--> suggestion: re-strucure text and add unfoldable sections (so that there is nor more feeling of infinity scrolling) 
- your need kind of incentive so that users will investigate into PP
--> add graphics / charts (two dimensional table aka. what can be influenced manually) / images
- add necessity to accept PP (at the end!)
--> user has to scroll down (note: could also increase bouncing rate)
- add active LINK (PP) to website // Link in Chrome seems broken 
--> users can inform thereselves right before installing the app
- suggestions: split regarding use case
--> no overload right at the beginning, just information when user is in contact with use case (e.g: register test)


finally conclude with – BENEFIT
better PP contributes to:
- transparency
- trust
- understanding
--> be bold and disclose that PP is very important topic to this app

**Comment by julizet** [comment]
Hier kommt mein Vorschlag für das Issue. Die Struktur (3 Headlines) ist eine Vorlage aus dem offiziellem Repo und sollten wir beibehalten. 
@Erdanf @linuxhelf : bitte um Review :)

## Current Implementation
Many users are still struggling with privacy concerns when using the app. However, current visualization and structure of the privacy policy feel like "infinity scrolling" and the overall plain visualization does not attract user to read the privacy policy in its full length. Status now, there are no unfoldable areas, highlighted areas, supporting links for explanation or icons or even images/models are used.   

## Suggested Enhancement
Make the the dry text of privacy policy more appealing in order to gain more transparency, trust and understanding towards the user. Researched showed that the usage of a variety of "telling" icons, models and diagrams can help users to understand PP better and let users
recognize which service providers are requesting which kind of data. Also adding credentials and/or showing a section – e.g. in the footer of the app – which is linking directly towards the PP could have a positive impact.

## Expected Benefits
Create a better understanding for the user and thus increase acceptance for the app

**Comment by Erdnaf** [comment]
Ja ist gut, 
ist zwar noch nicht alles drin, was wir letztendlich wollen, aber zum Vorfühlen denke ich sehr gut.

Als Titel vielelicht: **Improve Readability of Privacy Policy**

**Comment by linuxhelf** [comment]
sieht gut aus
der Vorschlag zum Titel gefällt mir auch
Ein paar Kleinigkeiten:

- im ersten Absatz: "... for explanation or icons or even ..." würde ich das erste "or" durch ein Komma ersetzen
- 2. Absatz: "Researched": soll das "Research" oder "Researchers" sein?
- "credentials": unter credentials verstehe ich meist zugangsdaten, ich nehme an hier ist Verweis gemeint? ich würde hier ein anderes Wort bevorzugen, z.b. "references"?
- eine Sektion im Footer der App... bin mir unsicher, bei Android ist sie oben Rechts unter App-Informationen -> Datenschutzinformation
worum geht es dir hier, sie sichtbarer zu machen?
- zum letzten Absatz: ich bin mir unsicher ob ein besseres Verständnis der Nutzer, die die App installieren dazu führt das mehr Nutzer die App installieren :D
es sorgt höchstens dazu, das weniger sie deinstallieren
um mehr zum installieren zu bringen, sollte es zusätzlich auch einfacher werden, die Datenschutzerklärung vor installation der App zu finden, z.b. indem sie nicht nur auf der Webseite hochgeladen wird, sondern dort auch aktiv verlinkt/beworben wird
meintest du das vorher bei " Also adding credentials and/or showing a section"? falls ja, sollte man da klarer sein, dass man auch die Webseite meint

die Frage ist auch im allgemeinen noch, in welches Repo wir das posten
es betrifft ja nicht nur android/ios/webseite sondern alle drei
evtl. documentation? oder  "wishlist" (scheint für "feature"-requests zu sein)?

**Comment by Erdnaf** [comment]
> zum letzten Absatz: ich bin mir unsicher ob ein besseres Verständnis der Nutzer, die die App installieren dazu führt das mehr Nutzer die App installieren :D
es sorgt höchstens dazu, das weniger sie deinstallieren
um mehr zum installieren zu bringen, sollte es zusätzlich auch einfacher werden, die Datenschutzerklärung vor installation der App zu finden, z.b. indem sie nicht nur auf der Webseite hochgeladen wird, sondern dort auch aktiv verlinkt/beworben wird
meintest du das vorher bei " Also adding credentials and/or showing a section"? falls ja, sollte man da klarer sein, dass man auch die Webseite meint

Vielleicht ganz klar: _Also adding the Privacy Policy to the Website, that everyone can read it before the app is installed_. Vielleicht auch anstatt das mit dem Footer, ich denke auch, die PP ist schon prominent genug und dafür würde ich keinen Footer aufmachen

> die Frage ist auch im allgemeinen noch, in welches Repo wir das posten
es betrifft ja nicht nur android/ios/webseite sondern alle drei
evtl. documentation? oder "wishlist" (scheint für "feature"-requests zu sein)?

Ich danke da ist [Whishlist](https://github.com/corona-warn-app/cwa-wishlist) am besten. Das scheint ein neues Repo zu sein um die Feature Requestst von den technischen Dingen zu trennen

**Comment by julizet** [comment]
hier kommt die angepasste Version gemäß eures Feedbacks.
@Erdanf & @linuxhelf: ist das so ok für euch? Wenn ja, dann würde ich es gerne heute noch in die [Wishlist](https://github.com/corona-warn-app/cwa-wishlist) posten. Denke als Gesprächsgrundlage sollten wir nicht zu kritisch mit uns selbst sein und finde wir haben die wichtigsten Punkte drin

## Current Implementation
Many users are still struggling with privacy concerns when using the app. However, current visualization and structure of the privacy policy feel like "infinity scrolling" and the overall plain visualization does not attract user to read the privacy policy in its full length. Status now, there are no unfoldable areas, highlighted areas, supporting links for explanation, icons or even images/models are used.   

## Suggested Enhancement
Make the the dry text of privacy policy more appealing in order to gain more transparency, trust and understanding towards the user. Research showed that the usage of a variety of "telling" icons, models and diagrams can help users to understand PP better and let users
recognize which service providers are requesting which kind of data. Also adding the author`s credentials or links to the legal texts of the General Data Protection Regulation (GDPR) can have a positive impact.

## Expected Benefits
Create a **better understanding** for the user and thus **increase acceptance** for the app. Furthermore, **increase willingness** (of people who are still sceptical) **to install the app** by by advertising and pre-reading the privacy policy directly on the website.

**Comment by Erdnaf** [comment]
Sehr gut. Im letzten Satz ist noch ein _by_ zu viel, aber dann kann das raus 👍

**Comment by linuxhelf** [comment]
ja, sieht gut aus und kann so raus, aber eine (letzte 😄 ) Kleinigkeit habe ich noch 
> Status now, there **are** no unfoldable areas, highlighted areas, supporting links for explanation, icons or even images/models **are** used.

evtl. das hintere "are" weg?

**Comment by julizet** [comment]
Danke für euer zweites Review.
Ihr findet das Issue [hier](https://github.com/corona-warn-app/cwa-wishlist/issues/16)
