### ISSUE TITLE
Grafiken & Optik 

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#150]
# Bounty / Aufgabe

Grafik erstellen, um Datenaustausch zwischen den Entities zu verdeutlichen

## Scope / Umfang

- Entities identifizieren (Server, App, Nutzer*in, Labor) 
- Daten identifizieren (TAN, TeleTAN, )

## Deliverables

- Grafik (einfach verständlich)

## Gain for the project / Nutzen für das Projekt

- fachliche Richtigkeit

## Roles / Rollen

bounty worker: @linuxhelf
bounty reviewer: @Erdanf @julizet

**Comment by julizet** [comment]
**Please find a first scrollable version of the prototype here:**
https://www.figma.com/proto/P9Lw06cpkS9KC9XIlPqjG3/FirstVersion?node-id=12%3A65&scaling=scale-down

**How to collaborate:**
1. create a Figma account
2. comment your email in this section and mention @julizet so I cann add you to the Figma collab team
3. happy prototyping

**Getting started with Figma**
https://www.youtube.com/watch?v=DSrbwCrEIII&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=3

**Comment by linuxhelf** [comment]
Entities

- Server
- App
- RKI
- Nutzer
- Labor

=> kommen selten vor und würde meiner Meinung nach wenig bringen/nur ablenken wenn man sie visualisiert

Daten

- Infektionsrisiko
- Zugriffsdaten (IP, zeitpunkt, Datenmenge)
- Begegnungsdaten (zufalls-IDs, datum, dauer, signalstärke) - 14Tage - im Apple-Google-Framework
- TAN/TeleTan/Token
- Testergebnis

=> kommen zu selten vor

Aktionen

- Risiko-Ermittlung
- Test registrieren
- Testergebnis teilen

=> siehe Ideen

-------------
Ideen:
-  zwei Paragraphen die fast nur Gesetzesartikel erwähnen -> Paragraph-Icon davor und einrücken (wie Zitat hier in Github)?#

> beispiel wie das eingerückte aussehen könnte

-  manche Sachen die nur Apple/Android betreffen mit Apple/Android Icon versehen und einrücken?diese könnten auf dem entsprechend anderem System standardmäßig eingeklappt sein?
-  Wenn man nur bestimmte Features nutzt, anbieten nach Features zu filtern, sodass ungenutzte Features z.b. ausgeblendet werden?
dann aber, wenn man später das Feature aktiviert, die zusätzlichen Beitrage anzeigen (z.b. Frage: wollen sie die gesamte Datenschutzerklärung sehen oder erstmal nur das, was sie betrifft und weiteres sobald ich entsprechendes Feature aktiviere?)
zumindest Features hervorheben, da jedes Feature 3-4 mal vorkommt!
-  Kapitel 7: Berechtigungen: Hier könnte man evtl. je ein Icon pro Berechtigung machen?
am besten das gleich wie normaler weise im Store bei den Berechtigungen verwendet wird

Das würde das selektive Lesen vereinfachen, da man so Sachen weglassen kann, die einen nicht betreffen
man bräuchte aber gute Icons für die 3 Aktionen

-----------------

Grafiken:
vereinfachte Kommunikation der 3 Aktionen mit teilnehmern + Daten?
evtl. Legende welches Icon welche Daten sind + Zeitangabe wie lange sie wo bleiben
ich werde mal probieren ein paar zu skizzieren

**Comment by linuxhelf** [comment]
https://www.figma.com/file/MOpBt3styqOKc2Us4wErCR/FirstVersion-Icons

**Comment by linuxhelf** [comment]
habe die Änderungen jetzt in #185 übertragen
- Icons für Android + Rechte bei 7.
- einrückung + paragraph bei gesetzes Texten
- Icons für die 3 Use-Cases
Bitte review machen

**Comment by Erdnaf** [comment]
Sieht gut aus.
Ich hab noch eine Transition hinzugefügt, damit es auch auf dem Protoypen sichtbar ist

**Comment by julizet** [comment]
Icons und Logos sind schick!

Nutzung im Prototypen (mit anderer Einspiegelung (linksbündig)): https://www.figma.com/file/sopIMcNqDFLYZ6sf3rVtbt/Colapsibile-Icons?node-id=79%3A1
