### ISSUE TITLE
Formatierung

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#151]
Bugs, die aufgefallen sind:

**Formatierung (in Android)**
nur in Deutsch:
5c ist 5a
5a, 5b, 6d ist strong statt h3
1 Letzter Absatz Klammer zu viel

**Comment by linuxhelf** [comment]
ich mache gleich den Pullrequest

**Comment by linuxhelf** [comment]
https://github.com/corona-warn-app/cwa-app-android/pull/589
