### ISSUE TITLE
new content - team contribution

### ISSUE THREAD

**Issue by omerhod** [FUB-HCC/20-SWP-CodingOpenness#156]
## Bounty
- have a new team contribution section in the website

## Scope
- S 5hr

## Deliverables
- add content on new Contribution Tab

## Gain for the project
- list our team's concrete contributions to the Official Corona Warn App

## Roles

bounty worker: @tratond01 
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by metaspice** [comment]
For starters, we should mention @JuliusBro's contribution to the official corona warn app documentation: https://github.com/corona-warn-app/cwa-app-android/issues/381
