### ISSUE TITLE
Fragebogen - Auswahl der Fragebereiche und der Fragen

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#16]
# Bounty / Aufgabe
 - [x] Auswahl, welche Fragen wir nehmen
 - [x] Festlegen der Struktur, welche Bereiche, Reihenfolge
- Wie erzeugen wir einen guten "Fluss"
- Wie verhindern wir ein "Abdriften" der Benutzer (+ Kontrollfragen, ob der Nutzer noch aufmerksam ist, Fortschrittsbalken)
- Können wir bestimmte Effekte durch die Reihenfolge hervorrufen/vermeiden
-  [ ] Pro Fragencluster ein Ziel/Zweck dieses Clusters formulieren, damit man neue Fragen in diesem  Cluster schaffen kann oder alte verwerfen, wenn sie diesem Zweck nicht dienen
- [x] Generische Pattern für Antwortmöglichkeiten (z.B. sehr viel - viel - wenig - gar nicht)
- [ ] Review jedes Bereiches, Formulieren der Fragen und der Antwortmöglichkeiten

## Scope / Umfang

- Fragenbereiche definieren
- Fragen zu Fragenbereichen formulieren
- Struktur & Reihenfolge logisch und repräsentativ aufbauen

## Deliverables

- erster initialer Entwurf des Fragebogens

## Gain for the project / Nutzen für das Projekt

- Ausgangspunkt für weitere Überarbeitungen 

## Roles / Rollen

bounty worker: @bernd96 
bounty reviewer: @julizet 

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by julizet** [comment]
LimeSurvey ist eingerichet

**Comment by Clearwood** [comment]
Bitte fügt die Priorität hinzu, weiterhin nutzt bitte das Template aus. 
In Scope sollte nicht der zeitliche sondern der inhaltliche Umfang ausgeführt werden.
Auch die Deliverables sind nicht irrelevant hier sollte auf die Umsetzung eingegangen werden.
Wie dokumentiert ihr euren Fortschritt? Über eine Wiki-Seite?

**Comment by julizet** [comment]
Bounty-Template wurde aktualisiert.

Da der erste Intiale Entwurf des Fragebogens (also das Deliverable dieses Issues) bereits erstellt wurde, wird dieser Bounty geschlossen.

Die Überarbeitung des Fragebogens wird in Issue #37 ([Link](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/37)) durchgeführt
