### ISSUE TITLE
Struktur / Unfoldable Areas / Navigation

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#168]
# Bounty
Protoyp zu onfoldable Areas erstellen
## Scope

-

## Deliverables

- Protoyp in Figma

## Gain for the project

-

## Roles

bounty worker: @Erdanf 
bounty reviewer: @molpremotone 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Erdnaf** [comment]
Vielen Dank für die Vorarbeit von @kraleva in #185 
Ich hab mit den Smart-Transitions echte Unfoldable Areas hinbekommen für die Abschnitte 1 und 5. Das reicht auch denke ich erstmal, damit man das Prinzip versteht. Bei 5 gibt es noch eine Schachtelung in a, b und c, die hab ich auch eingebaut. 
Ich hab das Projet wieder geklont, der neue Link ist [hier](https://www.figma.com/file/sopIMcNqDFLYZ6sf3rVtbt/Colapsibile-Test?node-id=0%3A1)
Und den Prototyp findet ihr [hier](https://www.figma.com/proto/sopIMcNqDFLYZ6sf3rVtbt/Colapsibile-Test?node-id=0%3A1&scaling=scale-down)

bitte um Review von @molpremotone

**Comment by molpremotone** [comment]
@Erdanf Sieht gut aus. Ggf. könnte es sinnvoll sein, die Untersektionen a, b und c grafisch anders darzustellen (wenn möglich), um sie optisch von den Sektionen 1, 2, ... stärker abzugrenzen.
