### ISSUE TITLE
Integration of Exposure Information on Github und Webseite

### ISSUE THREAD

**Issue by clmb** [FUB-HCC/20-SWP-CodingOpenness#181]
# Bounty

## Scope

- Die bestehende Beschreibung (https://www.overleaf.com/project/5ef20fd2062985000183f677) sollte 
sollte ins Wiki überführt und verkürzt bzw. visualisiert auf die Webseite.

## Deliverables

- Beschreibung im Wiki
- Beschreibung auf Webseite

## Gain for the project

- Transparenz :)

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by molpremotone** [comment]
Ich habe eine Verlinkung auf eine neue Seite "Exposure Notification API" im Abschnitt "Technische Ansätze der Corona-Tracing-App" hinzugefügt, erbete Review.
