### ISSUE TITLE
Idee: TeamPhoto?

### ISSUE THREAD

**Issue by omerhod** [FUB-HCC/20-SWP-CodingOpenness#184]
Bekommen wir vielleicht ein Teamphoto hin? Das wir uns einmal alle die Kamera an haben? Was halten Sie davon?

**Comment by Erdnaf** [comment]
Ist es dann nicht einfacher, wenn alle dem Team Wesbseite ein Foto schicken und ihr baut die dann zusammen? Es haben nicht alle eine Webcam glaube ich
