### ISSUE TITLE
Prototyping in Figma

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#185]
# Bounty

## Scope

- initial Setup of Figma
this means: setup style page, steup prototype page adding colors, fonty styles, fixed and scrollable areas etc.

- add Datenschutz text to Prototype
- add icons
- restructure (if needed)

## Deliverables

- Figma link for collaboration (plase mind: only to editors can work simultaniously)

## Gain for the project

- Develop a shiny prototype

## Roles

bounty worker: @julizet 
bounty reviewer: @kraleva 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by julizet** [comment]
**Please find a first scrollable version of the prototype here:**
https://www.figma.com/proto/P9Lw06cpkS9KC9XIlPqjG3/FirstVersion?node-id=12%3A65&scaling=scale-down

**How to collaborate:**
1. create a Figma account
2. comment your email in this section and mention @julizet so I cann add you to the Figma collab team
3. happy prototyping

**Getting started with Figma**
https://www.youtube.com/watch?v=DSrbwCrEIII&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=3

**Comment by julizet** [comment]
**Open the project with this link** (view access only, email invitation needed):
https://www.figma.com/file/P9Lw06cpkS9KC9XIlPqjG3/FirstVersion?node-id=12%3A65

**Device Setting**
Within the right sidebar you can find the Prototype Settings. I set the preference to Google Nexus 5X. By clicking on the Play-Button to the very top right of the browser window, a new tab will open to show the scrollable App. You will mention that I fixed the status bar to the top of the device and made the whole text area scrollable. 

Nice / short video about Devices and scrolling:
https://www.youtube.com/watch?v=ST6DOO11zuA&t=8s	

**Frame Setting**
Within the left sidebar you’ll find two Frames. We use „Working Frame Google Nexus 5X“ for our Prototype. The other Frame was just a test and can be deleted or used for further tests (if you like). 

**Pages & Styles**
One good thing about Sigma are the pages. You can use them to create several user testing prototypes or to simply add a „Style“ page to our project. In our project you’ll find a „Prototype“ page and a „Style“ page. Within the Style page you can find alle the official colors and font styles.

**Download Plugin for Figma „Android UI Kit“** (if you want to exchange some native Android elements)
https://www.figmacrush.com/figma-android-ui-kit/

**Comment by julizet** [comment]
Please find some further isntructions below

**Protype Page**
<img width="851" alt="Bildschirmfoto 2020-06-26 um 19 09 16" src="https://user-images.githubusercontent.com/52455010/85884085-541e8680-b7e2-11ea-9d4f-88d0339d0d44.png">

**Style Page**
<img width="943" alt="Bildschirmfoto 2020-06-26 um 19 04 54" src="https://user-images.githubusercontent.com/52455010/85884043-4406a700-b7e2-11ea-863c-0f7218fbdcb5.png">

**Comment by Erdnaf** [comment]
Cooler Prototyp, ist es Absicht, dass da nur die ersten zwei Absätze drin sind?
meine Email @julizet : claas.fandre@posteo.de

**Comment by julizet** [comment]
Danke. Das hatte ich vergessen zu erwähnen. Viktoriya hat erst am Samstag/Sonntag Zeit um sich um den Prototypen zu kümmern.  @kraleva kannst du den restlichen Text bitte ergänzen und ggf. die Anpassungen von diesem [Issue](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/168) einfügen?

@Erdanf hab dich hinzugefügt :)

**Comment by kraleva** [comment]
> Danke. Das hatte ich vergessen zu erwähnen. Viktoriya hat erst am Samstag/Sonntag Zeit um sich um den Prototypen zu kümmern.  @kraleva kannst du den restlichen Text bitte ergänzen und ggf. die Anpassungen von diesem [Issue](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/168) einfügen?
> 
> @Erdanf hab dich hinzugefügt :)

ja gerne ich machs morgen und übermorgen

**Comment by linuxhelf** [comment]
@julizet
meine Email: linuxhelf@gmail.com

**Comment by kraleva** [comment]
@julizet 
viktoriakraleva@gmail.com

**Comment by kraleva** [comment]
> Danke. Das hatte ich vergessen zu erwähnen. Viktoriya hat erst am Samstag/Sonntag Zeit um sich um den Prototypen zu kümmern. @kraleva kannst du den restlichen Text bitte ergänzen und ggf. die Anpassungen von diesem [Issue](https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/168) einfügen?
> 
> @Erdanf hab dich hinzugefügt :)

Die issue ist quazi leer, so ich weiß nicht wie ihr das unfoldable areas sich vorstellt, ich werde heute den restlichen Test einfügen, wenn ich natürlich die Zugangsrechte von euch kriege.

**Comment by julizet** [comment]
ok, hab dich hinzugefügt :)

@linuxhelf & @Erdanf: wie steht es um die Struktur und die Icons? Gibt es bereits etwas, was Viktorya im Prototypen berücksichtigen kann/soll?

**Comment by kraleva** [comment]
Ich hab das Projekt dupliziert und local bei mir erweitert, da ich nicht auf die Zugangsrechten warten wollte. 
[Hier](https://www.figma.com/proto/GUeWLbtlz9WeRCIAGnTbYg/FirstVersion-Copy?node-id=12%3A65&scaling=scale-down) ist das Link für das Prototype-Preview.
[Hier](https://www.figma.com/file/GUeWLbtlz9WeRCIAGnTbYg/FirstVersion-Copy?node-id=0%3A1) könnte man das bearbeiten (ihr braucht keine Einladung).
Ich werde mich bei Hilfe und Ideen bei den Dropdowns sehr viel freuen :) @julizet wenn du auch bessere Vorstellung hast wie diese Organisiert sein sollten und aussehen sollten, kannst du die entweder Dokumentieren oder auch hinzufügen, da ich erst ab diese Woche in der Gruppe bin und nicht so klare Vorstellung habe wie genau das aussehen sollte. Es wäre auch toll wenn die obenbezeichnete Issue ein bisschen mehr Informationen liefern könnte.

**Comment by kraleva** [comment]
Ich hab auch heute ein bisschen recherchiert, wie man "collapsing lists" in figma einblenden könnte, leider kann ich mich nicht vorstellen wie das erfolgen sollte. Die zwei Problemen dabei sind, dass entweder man ein Screen bei jedem Expandable machen sollte (da die nächsten Zeilen nach dem Collapse-Open) nach unten verschoben werden sollten, oder man könnte figma Overlays nutzen, wobei auch das selbe Problem existiert, mann könnte die unteren Zeilen nicht nach unten verschieben. 
Hier könnt ihr wahrscheinlich besser sehen was ich meine: (Dies ist nur eine Testdatei von mir, aber ich glaube, dass wenn ihr bei Transitions geht, ist und das laufen lässt wird es relativ klar worüber ich spreche). 
Mein Idee war bei jeder der Stichpunkten sowas zu machen: [Idee](https://www.npmjs.com/package/react-native-collapsible-list)
Meine Versuche bisher das mit Figma zu erreichen: [Hier](https://www.figma.com/file/5VD9jd6YAXzU5aYJO3AfGS/FirstVersion-Copy-Copy?node-id=79%3A1)
Ihr könnt ruhig da auch sachen ausprobieren, Zugangsrechten zum Bearbeiten kriegt ihr mit dem Link.

**Comment by Erdnaf** [comment]
Hier die Links zu den aktuellen Dokumenten:
[Edit](https://www.figma.com/file/sopIMcNqDFLYZ6sf3rVtbt/Colapsibile-Test?node-id=0%3A1)
[Prototyp](https://www.figma.com/proto/sopIMcNqDFLYZ6sf3rVtbt/Colapsibile-Test?node-id=93%3A0&scaling=scale-down)

**Comment by julizet** [comment]
prototyping is done. Just some minor, finetunign changes (if needed) --> close this issue
