### ISSUE TITLE
Anschreiben für Einladungsmail

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#198]
Texte formulieren (verbindlich, persönlich etc.) für die Verteilung
- Whatsappstatus
- email
- chat
- ...?
https://docs.google.com/spreadsheets/d/11Bc9eNNtMrPBBzKfnVwOEq1tPzWS_UW4d5iWS6HFKlI/edit#gid=1907178750

**Comment by bernd96** [comment]
Hey Bob,

na, schon die Corona-App installiert? ;-)

Ich mache grade dieses Semester ein Softwareprojekt über die App. Dabei interessiert uns vor allem auch, wie so die Gesamtbevölkerung die App sieht, welche Hinderungsgründe es gibt usw.
Dazu haben wir eine Umfrage erstellt, die jetzt auf freudige Teilnehmer wartet ;-)

Könntest du mir einen Gefallen tun und die Umfrage ausfüllen? Das würde uns mega weiterhelfen!
Du musst dafür nicht die App installiert haben.
Hier ist der Link dazu: https://tinyurl.com/akzeptanz-corona-tracing-app
Du kannst gerne auch den Link an andere weiterreichen, die das vielleicht auch interessieren würde!

LG
Alice

**Comment by bernd96** [comment]
Hallo Herr Mustermann,

bislang wurde die Corona-Warn-App von 14 Millionen Nutzern heruntergeladen. In einem Softwareprojekt der Freien Universität Berlin wollen wir untersuchen, welche Gründe es gibt, diese App zu installieren und zu benutzen - und welche Bedenken dagegen sprechen. 
Wir würden uns sehr freuen, wenn Sie uns dabei unterstützen und diese Umfrage zur Corona-Warn-App ausfüllen können (Sie müssen die App dabei nicht installiert haben): https://tinyurl.com/akzeptanz-corona-tracing-app

Viele Grüße
Bella Beispiel

**Comment by bernd96** [comment]
Die Corona-Warn-App - Was spricht dafür, welche Bedenken gibt es dagegen? Das untersuche ich grade mit anderen Studenten in einem Softwareprojekt der FU. Ihr würdet mir sehr helfen, wenn ihr diese Umfrage ausfüllen würdet: https://tinyurl.com/akzeptanz-corona-tracing-app

**Comment by bernd96** [comment]
Hey Ihr,

na, schon die Corona-App installiert? ;-)

Ich mache grade dieses Semester ein Softwareprojekt über die App. Dabei interessiert uns vor allem auch, wie so die Gesamtbevölkerung die App sieht, welche Hinderungsgründe es gibt usw.
Dazu haben wir eine Umfrage erstellt, die jetzt auf freudige Teilnehmer wartet ;-)

Könntet Ihr mir einen Gefallen tun und die Umfrage ausfüllen? Das würde uns mega weiterhelfen! (Ihr müsst die App dazu nicht installiert haben)
Hier ist der Link dazu: https://tinyurl.com/akzeptanz-corona-tracing-app
Ihr könnt gerne auch den Link an andere weiterreichen, die das vielleicht auch interessieren würde!

LG
Alice

**Comment by eagle-seagull** [comment]
Reviewed. Die Texte sind in Ordnung.
