### ISSUE TITLE
Konzept überlegen für die Verteilung

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#199]
Anfrage raus an alle Kommilitonen dieses Softwareprojekts + Motivationssprüche ("Gemeinsam können wir viele erreichen!")
Jeder schreibt min. 10 Leute an
- über 50
- unter 20
- in Ausbildung
- Student
- abgeschlossene Ausbildung
- abgeschlossener Universitätsabschluss
- nahe Familie
- entfernte Familie
- andere Stadt
- lebt in einer ländlichen Umgebung
- Nachbarschaft

+ Hilfestellungen wie wir leute erreichen (whatsapp, persönlich, email, telefon...) +  texte aus dem anderen issue

**Comment by eagle-seagull** [comment]
- QR Code + Verkürzter Link erstellt.
- Anschreiben formuliert

Hallo Zusammen, jetzt geht's ans Eingemachte!
Der Fragebogen ist fertiggestellt und kann verteilt werden. Wenn jeder 10 verschiedene Personen erreicht, haben wir schon eine gute Aussagekraft erreicht.

Um die Verteilung für euch etwas einfacher zu machen, schlagen wir euch hier Kategorien vor. Am besten wäre es wenn ihr eine Person je Kategorie anschreiben könnt (es sind 11 Kategorien, also ihr könnt eine auslassen).

Das wäre je eine Person:
    • über 50 Jahre
    • unter 20 Jahre
    • in Ausbildung
    • im Studium
    • mit abgeschlossener Ausbildung
    • mit abgeschlossenem Universitätsabschluss
    • naher Familie
    • entfernter Familie
    • aus anderer Stadt
    • in ländlicher Umgebung lebend
    • aus der Nachbarschaft

Natürlich kann jeder Teilnehmer den Link an Weitere schicken!

Wie könnt ihr den Bogen verteilen?
    URL direkt zur Umfrage: https://tinyurl.com/akzeptanz-corona-tracing-app
    QR-Code mit obigen Link:
![qr-survey](https://user-images.githubusercontent.com/64364916/86250333-bbf11a80-bbb0-11ea-9074-b721b77d02c4.png)
