### ISSUE TITLE
 Vergleich der Ansätze

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#2]
TODO: Aufarbeitung der bestehenden Recherche hinzu einem Vergleich bezüglich (1)  Architektur (2) Kommunikationsablauf

**Comment by Erdnaf** [comment]
Ich mach hier mal den Anfang für Kriterien, die vielleicht sinvoll sind:

Architektur:
- Zentral/Dezentral
- Vergleich der ID's (Auf dem Telefon, oder Server)

Kommunikationsablauf:

- Kommunikation verschlüsselt?
- Wie wird benachrichtigt (Push oder Poll)
- Server kann die Apps identifizieren
- Datenmenge (die das Netzwerk belastet)
- Kann zweitkontakt feststellen

ergänzt gerne

**Comment by linuxhelf** [comment]
Ich glaube das sind schon die wesentlichen Punkte, auf die schnelle fällt mir z.b. folgendes ein

nicht direkt technisch, aber wahrscheinlich trotzdem sehr interessant:

- Unterstützer (also z.b. Google, Apple, konkrete Länder)

Evtl. redundant mit Vergleich der IDs
- welche Daten werden bei Infizierung konkret hochgeladen

bin mir unsicher ob interressant, da nicht wesentlich zum algorithmus:
- wie funktioniert Autorisierung durch Gesundheitsamt

habe ich noch keine Infos zu gesehen, könnte aber sehr wichtig sein:

- kann mit anderen Implementationen / anderen Ansätzen zusammenarbeiten

ist ähnlich zu Vergleich der Ids in Kombination mit Zweitkontakt
(für tracking von zweitkontakt,  muss man sich als Erstkontakt gegenüber dem Server erkenntlich zeigen/ausweisen)
- wie viel Informationen hat der Server über Infizierungen

**Comment by kraleva** [comment]
Ich würde auch dazu die Frage hinzufügen, inwie fern die Privatsphäre des Nutzers geschätzt wurde, da die größte Kritik bei PEPP-PT z.B. mit Datenschutz verbunden, so wir können auch in diesem Zusammenhang die Ansätze vergleichen.

**Comment by julizet** [comment]
Würde noch um den Themenbereich "Privatsphäre und gesellschaftliche Transparenz" erweiterin. Darin die Kategorien:
- Kontakt-Graph-Generierung
- Verarbeitung personenbezogener Daten
- Interoperabilität zu anderen Protokollen

Im Themenbereich "Architektur" könnte man noch die Kategorie "Ort der Rechenleistung" (Server Vs. Smartphone) aufnehmen

**Comment by clmb** [comment]
Es gibt bereits einige Vergleiche, vielleicht helfen diese beide Kriterien:
https://mobilsicher.de/ratgeber/corona-epidemie-eindaemmen-per-smarphone-diese-apps-stehen-zur-debatte
https://www.wu.ac.at/ec/projects/privacy-friendly-corona-virus-tools
https://secpriv.wien/blog/de/tracing-app/overview/
Ich denke, insbesondere der letzte Blogartikel ist sehr hilfreich.

**Comment by julizet** [comment]
Wiki-Page als Arbeitsdokument: [Hier entlang](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Vergleich-der-Ans%C3%A4tze)

Architektur: @julizet 
Kommunikationsablauf: @kraleva  & @Erdanf 
Privatsphäre: @bernd96 & @linuxhelf

**Comment by Erdnaf** [comment]
Ich denke wir sollten die Kategorie "MAC-Adressen-Übertragung" in "MAC-Adressen-Tracking" ädern und uns anschauen, wie das verhindert werden kann.

Hier ein Text vom dem Dokument von DCTS, dass dass gut erklärt:

> Bluetooth also advertises the mac-address of the device. From our observations
this address changes after a certain time and is also changed when
Bluetooth is activated. We were able to observe this behaviour in our tests on
Android 8 and 9 as well as iOS 12. We stop and restart advertising immediately
when updating the ID, such that the advertised mac-addresses change at the
same time as the IDs. This prevents any malicious association of a mac-address
to several IDs. These changing IDs keep the user anonymous and complicate
tracking.

**Comment by Erdnaf** [comment]
Arbeitsaufträge beim Treffen:
- [x] Einheitliche Benennung der Bluetooth ID's nach der Legende
- [x] Übertragene Informationen Trennen in upload und download
- [ ] Art der Generierung in Komunikation thematisieren
- [x] Verlinkung der Quellen

**Comment by clmb** [comment]
Ich habe gestern noch Feedback bezüglicher zweier Punkte von Prof. Wählisch erhalten. 

> Die Kategorien sind unscharf.
>
> * Ort der Speicherung:
> Server vs. Smartphone. Besser waere Server vs. Client.  ... Der 
> Erlaeuterungstext ist bei beiden Kategorien gleich. Was ist mit "Daten" 
> gemeint.
> 
> * Verfahren bei Aktualisierungen:
>  Broadcast an alle vs. Pull je Geraet. Push vs. Pull. Man koennte die 
> Clients auch per Broadcast informieren, ein Pull durchzufuehren -- wann 
> auch immer das Pull dann tatsaechlich passiert.

**Comment by clmb** [comment]
Broadcast beschreibt, an wen ich Daten verteile.

Pull bzw. Push, wie ich die Daten erhalte. 

Daher sollten diese beiden Perspektiven getrennt werden.

**Comment by clmb** [comment]
Bitte bauen Sie ein Experten-Panel auf, dass Sie bei dem Vergleich der Ansätze unterstützt. Prof. Wählisch wäre auch mit dabei und Sie können ihn anschreiben.

**Comment by clmb** [comment]
Ich kommentiere hier so rum, da es noch kein Board gibt. Ich würde gern Issues erstellen.

**Comment by Erdnaf** [comment]
ist auf andere Issues verteilt worden
