### ISSUE TITLE
Technische Umsetzung in Android - Data Privacy

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#202]
# Bounty
Evaluation der Möglichkeiten den Prototypen in Android umzusetzen

Aktueller Entwurf https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/185#issuecomment-652297918
## Scope

- Unfoldables
- Icons

## Deliverables

-

## Gain for the project

-

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by linuxhelf** [comment]
aus Zeitgründen werden wir eine Implementierung nicht mehr schaffen, ich füge hier nachher noch ein HowTo hinzu, wie man es implementieren könnte

**Comment by linuxhelf** [comment]
der Vorschlag/das HowTo ist jetzt im Wiki
https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki//Data-Privacy%3A-Implementation
ich würde mich über ein Review freuen

**Comment by Erdnaf** [comment]
Das HowTo ist gut 👍
