### ISSUE TITLE
Organisation der Projektboards

### ISSUE THREAD

**Issue by Clearwood** [FUB-HCC/20-SWP-CodingOpenness#24]
# Bounty / Aufgabe

Entwicklung von Richtlinien und Konzepten zur Nutzung von Kanban-Boards innerhalb des Softwareprojekts und Teilgruppen.

## Scope / Umfang

- Guidelines für die Nutzung unterschiedlicher Projektboards

## Deliverables

- erweiterte Dokumentation in Form von Markdown-Dateien

## Gain for the project / Nutzen für das Projekt

-

## Roles / Rollen

bounty worker: @adrianapintod 
bounty reviewer: @Clearwood 

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by adrianapintod** [comment]
This is available for review on https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Kanban-boards
