### ISSUE TITLE
Ressourcen aufbereiten

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#3]
TODO: Sammeln und Aufbereiten von Ressourcen, um schnell in die Android-Programmierung/Cross Plattform einzusteigen sowie Anlegen von ersten Beispielprojekten

**Comment by JuliusBro** [comment]
Würde jetzt erstmal sagen, jeder sucht einfach nach einigen nützlichen Dokus/Tutorials zum Einstieg in die Android-Entwicklung, dann vergleichen wir die einmal und nehmen die besten ins Wiki. Was meint ihr?

**Comment by DPHLong** [comment]
Hallo Leute, sollten wir eine Gruppen-Chat erstellen?

**Comment by DPHLong** [comment]
@JuliusBro ja finde ich gut!

**Comment by DPHLong** [comment]
Ich habe einen Android-Kurs von Udemy teilgenommen. Es kostet ja etwas, aber der Kurs ist sehr hilfreich und leicht zu verstehen.

Sonst kann ich diesen Web empfehlen:
https://www.thecrazyprogrammer.com/learn-android-programming

diese Seite ist sehr detailliert und frei zu lesen.

**Comment by Psychosadistic** [comment]
@DPHLong Danke für die Seite _-saved-_ und ein Gruppenchat wäre hilfreich.
Was hast du dir dabei gedacht - Discord?

Einige Bücher (PDF) / Videotutorials besitze ich übrigens und kann sicher davon etwas empfehlen. Bei Bedarf kann das ja ggf. über den Gruppenchat angesprochen werden.

___

### Wer gerne nachschlagen möchte

**Java**
- [Rheinwerk Verlag - Java ist auch eine Insel](https://www.rheinwerk-verlag.de/java-ist-auch-eine-insel_4804/)
- [Rheinwerk Openbook - Java ist auch eine Insel](http://openbook.rheinwerk-verlag.de/javainsel/)

**Kotlin**
- [Kotlin - Reference](https://kotlinlang.org/docs/reference/)

___

### Wer sich gerne belesen möchte

**Java**
- [Java-Intensivkurs - In 14 Tagen lernen Projekte erfolgreich zu realisieren](https://www.springer.com/de/book/9783642039546)

___

### Wer zugelabert werden und weniger lesen möchte

- [Derek Banas](https://www.youtube.com/channel/UCwRXb5dUK4cvsHbx-rGzSgw)
  - Kotlin: https://www.youtube.com/watch?v=H_oGi8uuDpA
  - Java: https://www.youtube.com/watch?v=n-xAqcBCws4

Sein Androidtutorial ist 7 Jahre alt ... :smile:

___

### Wer sich von einer schicken Webseite blenden lassen möchte

**Kotlin - Android**
- [Vogella](https://www.vogella.com/tutorials/Android/article.html) (wird oft empfohlen)
- [Android Developers](https://android-developers.de/) (deutschsprachiges Forum)
- [Google Codelabs](https://codelabs.developers.google.com/codelabs/build-your-first-android-app-kotlin/) (per Zufall darauf gestoßen)
  - weiterführende Links: [Udacity - Kotlin Bootcamp](https://www.udacity.com/course/kotlin-bootcamp-for-programmers--ud9011)
- [Kotlin for Android](https://kotlinlang.org/docs/reference/android-overview.html)

**Comment by DPHLong** [comment]
@Psychosadistic ja ist auch gut. Ich kenne aber leider discord nicht gut aus. Sonst Telegram ist ein andere Vorschlag

**Comment by dennisn00** [comment]
Ich denke, wir sollten auch ganz kurz zeigen, welche IDEs man verwenden sollte/könnte. Ich hab bisher nur mit Android Studio gearbeitet, gibt es weitere bedeutende IDEs? IntelliJ kann man ja auch benutzen, ist das besser als Android Studio?

**Comment by JohBrose** [comment]
Ich persönlich bevorzuge IntelliJ da ich auch sonst mit arbeite und man mit der Uni-Mail Zugriff auf Ultimate bekommt

**Comment by JuliusBro** [comment]
android studio ist ja quasi IntelliJ, baut jedenfalls darauf auf und wer sich mit IntelliJ auskennt kann auch gut mit android studio klarkommen.

**Comment by Psychosadistic** [comment]
[Android Studio](https://developer.android.com/studio) ist so gesehen eine für die Androidentwicklung angepasste (typische) [JetBrains](https://www.jetbrains.com/)-IDE.
Entsprechend ist IntelliJ genauso gut geeignet, wenngleich gegebenenfalls Plugins nachinstalliert werden müssen.

Grundsätzlich gibt es (zu) viele solcher Tools:
- [Visual Studio](https://visualstudio.microsoft.com/de/vs/android/) (zur anderen Seite wechseln :see_no_evil:)
- [AIDE](https://www.android-ide.com/) (direkt auf dem :phone: coden)
- [Komodo IDE](https://www.activestate.com/products/komodo-ide/) (sieht interessant aus :smiley:)

Rein theoretisch kann man sich auch NetBeans oder Eclipse antun ... _(bitte nicht :skull:)_

Sich auf eine Umgebung zu einigen mag sicherlich Vorteile mit sich bringen; die Notwendigkeit sollte allerdings nicht bestehen. Ich gehe davon aus, jeder weiß, wie mit der (bereits) genutzten IDE umzugehen ist.

Bei Fragen kann ja dann der (zukünftige) Gruppenchat dazu beitragen, mögliche Unklarheiten im Umgang mit den IDEs zu beseitigen oder Traumata durch _vi_ zu bekämpfen. :smiling_imp:

Ich tendiere übrigens auch eher zu Android Studio. :+1:

**Comment by DPHLong** [comment]
mir ist Android Studio ist am besten :)

**Comment by DPHLong** [comment]
Leute, ich habe eine Gruppe in Slack erstellt. Hier ist die Einladung
https://join.slack.com/t/swp20technikgruppe/shared_invite/zt-e755gbqa-_dueNUAuLWr4xAVRckvZ3g
sollte es nicht funktionieren, schreibt mir eure Email. ich lade euch ein.
Gruß
Long

**Comment by JuliusBro** [comment]
Vielleicht sollten wir auch nochmal speziell die Doku für Android-Studio hervorheben - und auch nochmal extra auf die Kotlin Koans aufmerksam machen, die bringen einem ziemlich schnell die Unterschiede zwischen Kotlin und Java bei.

**Koans:**
[https://play.kotlinlang.org/koans/overview](https://play.kotlinlang.org/koans/overview)
**Android Studio:**
[https://developer.android.com/studio/intro](https://developer.android.com/studio/intro)

**Comment by Clearwood** [comment]
Ist dieser Issue schon abgeschlossen?
Wenn nicht, erstellt bitte neue Bounties mit kleineren Teilbereichen oder als Erweiterung. Dieser Issue ist einerseits relativ alt und hat mit der Wiki-Seite andererseits schon ein Zwischenergebnis.
