### ISSUE TITLE
Fragebogen Review Prozess

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#31]
# Bounty
Überarbeitenden Fragebogen (Basis ist das GoogleDoc) von externen Expert*innen in 1-2 Zyklen testen lassen und im Anschluss überarbeiten

## Scope
- GoogleDoc an Expert*innen senden
- Feedback dokumentieren

## Deliverables
- Feedback aller Expert*innen in GoogleDoc eintragen und Fragebogen entsprechend anpassen

## Gain for the project
- konsolidiertes Feedback von CMB und weiteren Expert*innen/Professor*innen

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Clearwood** [comment]
@julizet Bitte nutzt auch hier das Template wie vorgesehen, hier fehlt noch eine zuständige Person und die Priorität.

**Comment by julizet** [comment]
Template angepasst und vervollständigt.
Es fehlt allerdings noch eine zuständige Person.
