### ISSUE TITLE
Vergleich der Ansätze - Migration zur Webseite

### ISSUE THREAD

**Issue by linuxhelf** [FUB-HCC/20-SWP-CodingOpenness#32]
# Bounty

Den Vergleich gleichzeitig in Wiki und Webseite zu pflegen ist aufwändig, wir würden vorschlagen ihn in die Webseite zu migrieren, dann kann man dort per Pull Request änderungen einpflegen.

## Scope

- Wiki-Seiten zum Vergleich in die Webseite einbinden
- Wiki-Seiten zum Vergleich löschen

## Deliverables

-

## Gain for the project

- keine Datenduplizierung
- nachvollziehbarere Strutktur

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/4

**Comment by linuxhelf** [comment]
siehe auch #38

**Comment by linuxhelf** [comment]
da #38 fertig ist, habe ich project-website-vergleich aktualisiert und die Markdown-datei in den richtigen Ordner gepackt und umbenannt

**Comment by linuxhelf** [comment]
@kraleva @Erdanf 
Wir sollten noch klären, welche anderen Seiten wir in die Webseite migrieren (alle Vergleichsseiten, wie sie aktuell im Wiki sind?)
und wie diese dann auf der Webseite aussehen sollen (was für ein Menü)

**Comment by Erdnaf** [comment]
Ich denke sinvoll wären die drei anfänglichen Konzepte (BP3T, DCTS, PEP PT) plus die Offizielle Corona Warn app. Zu den ersten würde ich die quasi aus dem Wiki übernehmen. Bei der Corona Warn App wollte Technik Team ja eine wiki Seite erstellen #43 

Vom Design her, würde ich was Ähnliches machen, wie das, was zur Zeit auf der Live Webseite unter "Gruppen" der Fall ist.

**Comment by linuxhelf** [comment]
der Tab "Gruppen" wurde bereits in "Ansätze" umbenannt
dass sollte man mit dem Vergleich Tab kombinieren und das Untermenü behalten, da stimme ich zu

**Comment by linuxhelf** [comment]
habe den branch `website/feat/vergleich-wiki-migration` erstellt

**Comment by linuxhelf** [comment]
ich habe mal ein Navbar erstellt und die Inhalte migriert
grobe TODO-liste:
- [ ] css schön machen
- [ ] code schön machen
- [ ] inhalte überarbeiten
- [ ] coronawarnapp seite befüllen
- [ ] Bilder im Markdown von lokal importieren
- [ ] Tab "Ansätze" entfernen?

**Comment by linuxhelf** [comment]
lokale Bilder funktionieren nur, wenn sie im public Ordner sind
falls sie unter Assets sind, werden sie von react umbenannt und verschoben
man kann zwar mit regex die bild aus dem markdown raussuchen, kann sie dann aber nicht durch die verschobenen Bilder ersetzen, da react dieses mapping nicht zur laufzeit erlaubt, nur zur compilezeit
