### ISSUE TITLE
Rest-Calls in Android genauer betrachten

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#33]
Aus vorherigen Projekten wissen wir, dass Rest-Calls gerne ein wenig schwieriger waren. Deswegen sollten wir uns diese noch einmal etwas genauer angucken.

# Bounty

## Scope

- 

## Deliverables

- Documentation

## Gain for the project

- More information

## Roles

bounty worker: @JohBrose 
bounty reviewer: @JuliusBro 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by JohBrose** [comment]
Macht es Sinn hierfür einen Dummy-server zum testen zu erstellen der für jede CRUD-Operation einfach nur OK bzw super simples JSON zurückgibt?
Wäre dann ein neues Issue

**Comment by JohBrose** [comment]
@JuliusBro hat leider etwas gedauret... bitte reviewen
