### ISSUE TITLE
Offizielle Corona Tracing App - Technikanalyse

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#35]
# Bounty
Wir müssen uns an der offiziellen Corona Tracing App orientieren.
## Scope

- aktuellen Status betrachten
- für uns relevante Technikansätze in Dokumentation niederlegen
- Fazit ziehen

## Deliverables

- fertige Dokumentation über relevante Technikansätze

## Gain for the project

- Grundbausteine, ohne die keine Programmierarbeit nicht stattfinden kann

## Roles

bounty worker: @JuliusBro @JohBrose @Psychosadistic @dennisn00 @DPHLong 
bounty reviewer: @JuliusBro 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Clearwood** [comment]
Der Reviewer muss unabhängig vom Bearbeiter sein, außerdem scheint die Zeiteinschätzung bei fünf Beteiligten zu gering.

**Comment by clmb** [comment]
Ich würde auch empfehlen, dass ein Bounty nur einer Person zugeordnet wird, da sonst die Verantwortlichkeit nicht klar ist.

**Comment by dennisn00** [comment]
Vielleicht sollten wir das Issue aufteilen. sodass je eine Person den Corona-Warn-App Server, den Verification Server und die App selbst näher betrachten und eine kurze Dokumentation erstellen?

**Comment by DPHLong** [comment]
Ich würde dann die App selbst betrachten und Doku erstellen :)
