### ISSUE TITLE
Fragebogen überarbeiten

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#37]
# Bounty
Siehe Email von CMB
Ablauf etc. überarbeiten
Überarbeitung in LimeSurvey ist zu aufwändig für eine kurze Feedbackloop
Vorschlag: Google Docs für leichtgewichtigen Austausch
Dieses Dokument kann dann an andere geschickt werden, die es ändern/kommentieren können.

## Scope

- aktuellen Fragebogen in shared Google Doc exportieren
- Feedback von CMB je Kategorie einarbeiten (nach Personen aufgeteilt)

## Deliverables

- Google Doc mit allen Fragen, welches an Frau CMB gesandt werden kann

## Gain for the project

- Bearbeitung und Feedback via Google Doc einholen, weil Feedback-Prozess sehr viel schneller und besser kooridniert werden kann, als in LimeSurvey

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Clearwood** [comment]
Was wollt ihr genau machen?
Soll es hier um inhaltliche Änderungen gehen oder nur darum ein Google Dokument zu erstellen, indem alle Fragen aufgeführt sind?
Priorität fehlt zudem + Bearbeiter/in

**Comment by julizet** [comment]
Überarbeitung & Vervollständig der Bounty-Beschreibung erfolgt.

Leider kann ich @molpremotone ([Profil-Link](https://github.com/molpremotone))nicht zum Bounty assignen, da er nicht in der Liste der "vorgeschlagenen" User auftaucht. Vielleicht kannst du hier helfen @Clearwood ? Kann mir vorstellen, dass er noch nicht der Gruppe zugehörig ist.
