### ISSUE TITLE
Improve markdown workflow

### ISSUE THREAD

**Issue by omerhod** [FUB-HCC/20-SWP-CodingOpenness#38]
# Bounty
#### Groom & implement:
- find a suitable library for appending a corresponding markdown file so we don't need to inline the wiki page content.

## Scope
`size-M` - 8hr

## Deliverables
- Updated code

## Gain for the project
- Improve workflow

## Roles
bounty worker: @Hod04  @tratond01 
bounty reviewer: @sontungg @oussab 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/5

**Comment by metaspice** [comment]
To be able to pull the website's content from the wiki markdown files, we need to have the website deployed on the master branch so the wiki's files are directly accessible.

----

The above will be handled and tracked within this issue: https://github.com/FUB-HCC/20-SWP-CodingOpenness/issues/40
