### ISSUE TITLE
GitHub Best Practices etablieren

### ISSUE THREAD

**Issue by Clearwood** [FUB-HCC/20-SWP-CodingOpenness#4]
# Bounty / Aufgabe
Diese Aufgabe soll Best Practices für dieses Projekt etablieren, sowie Werkzeuge ausprobieren. 

## Scope / Umfang

- [x] Contribution Guidelines
- [ ] Issue Template
- [ ] Pull Request Template
- [ ] Code of Conduct
- [ ] Github Projekt

## Deliverables

- Markdown Dokumente sowie Vorlagen, die das Mitarbeiten am Projekt vereinfachen
- Erstellung von einem Github Projekt

## Gain for the project / Nutzen für das Projekt

- Vereinfachung von Prozessen sowie bessere Organisation der Arbeit über Teams hinweg. 

## Roles / Rollen

bounty worker: @Clearwood @adrianapintod
bounty reviewer: @

**Comment by bernd96** [comment]
Hinweis von Linus: man kann mit 
<details><summary>Überschrift</summary>Detailtext, der erst durch aufklappen sichtbar wird</details> 
so ein Aufklappbares element erzeugen, dass ist z.b. hilfreich um rechts eine sidebar mit wichtigen seiten im wiki hinzuzufügen o.ä.
