### ISSUE TITLE
Kommunikation über die Corona Tracing App

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#41]
# Bounty

Kommunikation über die Entwiklungen der offiziellen  [Corona Warn App](https://github.com/corona-warn-app)

## Scope

- Kommunikation zwischen Team Technik und Team Vergleich

## Deliverables

- Verglelich

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by linuxhelf** [comment]
siehe auch #35

**Comment by kraleva** [comment]
Das Issue ist nicht mehr relevant, da die offizielle Dokumentation schon draußen ist, deswegen schließe ich dies ab.
