### ISSUE TITLE
Kurzdokumentation der offiziellen Corona-Warn-App erstellen

### ISSUE THREAD

**Issue by dennisn00** [FUB-HCC/20-SWP-CodingOpenness#43]
# Bounty
Wir müssen die offizielle Corona-Warn-App verstehen
## Scope
Dokumentation der offiziellen App vereinfachen und zusammenfassen, dabei Verbidnung zu untersuchten Ansätzen (PEPP-PT, DP-3T, DCTS) herstellen

## Deliverables
fertige, kurze Dokumentation als Wiki-Page

## Gain for the project

- Um an der App mitzuarbeiten, muss die Architektur verstanden werden, die Dokumentation soll ein schnelles Verständnis ermöglichen

## Roles

bounty worker: @dennisn00 
bounty reviewer: @JuliusBro 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Erdnaf** [comment]
Die Vergleichsseite haben wir schon fast fertiggestellt, verfolgbar unter #13 .
Was noch fehlt ist die Vorstellung auf einer einzelenen Seite im Detail.
Wir wollen außerdem das Fachliche aus dem Wiki raus und auf die Webseite migrieren, das wäre denke ich auch für diese Seite Sinvoll (#32)

**Comment by dennisn00** [comment]
Ich habe im Wiki eine Kurzdokumentation angefangen. Eine detailierte Dokumentation gibt es ja im Repo der offiziellen App. Ich denke, dass sich das nicht zu sehr mit dem Vergleich der Ansätze deckt. Wir können das auch gerne auf die Website kopieren, wenn es fertig ist

**Comment by clmb** [comment]
Wo befindet sich die Doku? Hier ist sie nicht als Link hinterlegt?

**Comment by clmb** [comment]
https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Kurzdokumentation-der-offiziellen-Corona-Warn-App

**Comment by dennisn00** [comment]
@JuliusBro bitte reviewen, damit wir das Issue hier abschließen können

**Comment by JuliusBro** [comment]
[x] Review ist fertig, kann abgeschlossen werden

**Comment by dennisn00** [comment]
Danke, @JuliusBro. Damit schließe ich das Issue. Das Ergebnis ist hier zu finden: 
https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Kurzdokumentation-der-offiziellen-Corona-Warn-App
