### ISSUE TITLE
Strukturgraph für den Fragebogen

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#57]
# Bounty
Erstellung eines Strukturgraphes für den Fragebogen.

> Wichtig ist, dass es noch die Struktur des Fragebogens klarer ist. Ich 
habe mal angefangen in draw.io die Struktur nachzuzeichnen. Das müssten 
Sie noch vervollständigen. Das brauchen Sie unbedingt, vor allem wenn 
der Fragebogen dann in LimeSurvey überführt wird.

## Scope

- Alle Fragen des Fragebogens, bzw. die Oberbereiche

## Deliverables

- Strukturgraph z.B. in draw.io

## Gain for the project

- Hilfreich für die spätere Einfügung in LimeSurvey
- Einfacher zu reviewen und zu verstehen wenn man die Struktur kennt

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by gancia-kiss** [comment]
- Felix (Initialer Vorschlag)
    - Linus (Initialer Vorschlag)
    - Ingrid (Review)

**Comment by linuxhelf** [comment]
Ergebnis:
https://drive.google.com/file/d/1Pn0bv9PAgVtEH8uZo8vj0nBfoWobGV7Y/view?usp=sharing

**Comment by linuxhelf** [comment]
Strukturgraph nach Review in #82 überarbeitet
