### ISSUE TITLE
Einleitung Fragebogen: Ausschnitte aus dem Comic verwenden

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#58]
# Bounty
Den Comic aus dem [DP3T-Projekt](https://github.com/DP-3T/documents/blob/master/public_engagement/cartoon/de/comic-de.pdf) verwenden, um den Einführungstext für den Fragebogen sinnvoll zu ergänzen oder zu ersetzen.
## Scope

- Nicht unbedingt den ganzen Comic übernehmen, sondern in dem Ausmaß dass es sinnvoll ist. Zumindest alle momentan in  Textform beschriebenen Infos sollten dort auftauchen
- Die Verständnis mit Zwischenfragen sicherstellen. Als Vorlage für die Zwischenfragen kann der  [Schweizer Fragebogen](https://mfr.de-1.osf.io/render?url=https://osf.io/2tnya/?direct%26mode=render%26action=download%26mode=render) dienen.

## Deliverables

- Schöne und nachvollziehbare Einführung in den Fragebogen
- Auch der absolute Laie fühlt sich informiert und abgeholt

## Gain for the project

- Fragebogen ist besser / Leichter verständlich

## Roles

bounty worker: @eagle-seagull 
bounty reviewer: @julizet 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by eagle-seagull** [comment]
Welche Infos stehen in den verschiedenen Quellen:
![image](https://user-images.githubusercontent.com/64364916/83147271-bc9d1980-a0f7-11ea-81a5-e4c667d74fea.png)

Fazit: Wir können das one-page Comic nehmen und mit einem Infotext Informationen dazu ergänzen.
Ich habe keine Informationen gesehen, ob man die Comics bearbeiten darf und werde das daher vorerst vermeiden. Wenn es doch erlaubt ist, habe ich den One page comic + Seite 02 als Erklärung von Tracing bereits erstellt.

	Was erklärt werden kann, wenn man den 1-page Comic nutzt:

	- [Entweder mit Seite 2 vom Comic oder in Textform] Contact Tracing Ansatz: Man ist ansteckend ohne Symptome, hat aber Zeit zum Erkennen einer Infektion
	- 60% Aller nötig
	- Kein GPS bei diesem Ansatz
	- Kompatibilität zwischen Corona-Apps
	- Last von Gesundheitsämtern nehmen
	- man kann nicht selbst die zufälligen IDs hochladen - nur mit medical Authorities
	- Nutzer kann beim Upload Zeiträume verschweigen
	- Nutzer kann selbst entscheiden, ob "die zufälligen IDs" geuploaded werden
	- Ist keine Corona Diagnose-App



Der Erklärungstext könnte zum Comic könnte so aussehen:

Alice und Bob haben im Comic gezeigt, wie eine Contact-Tracing App zur Eindämmung von COVID-19 beitragen und gleichzeitig unsere Rechte schützen kann. Dabei wurde Tracing mit Bluetooth beschrieben, was bedeutet, dass von der App kein GPS-Signal verwendet wird. Außerdem ist es nicht mal nötig, alle Kontakte zu finden, es genügen schon etwa 60%!*

Eine Tracing-App ist zwar kein Diagnosetool, um einen Corona-Test zu ersetzen, aber durch die schnelle Aufdeckung von potentiellen Infektionsketten wird die Arbeitlast des Gesundheitsamts erleichtert. 

Wenn man nach langem Kontakt zu erkrankten Personen eine Benachrichtigung von der App erhält und positiv auf Corona getestet wurde, kann man selbst entscheiden, ob man das gesagte Kauderwelsch hochladen möchte. Man kann auch nur bestimmte Zeiträume, z.B. die man nur zu Hause war, enthalten. Jegliches Hochladen wird aber nur durch medizinisches Fachpersonal gewährleistet, um Spam zu vermeiden.

*(Ferretti & Wymant et al. "Quantifying SARS-CoV-2 transmission suggests epidemic control with digital contact tracing." Science (2020).)

Ich habe bemerkt, dass es keine deutsche Version vom 1-page Comic gibt und habe diese Übersetzung gemacht. Falls man das normalerweise nicht verwenden darf, kann ich nach dem Review (und evtl. Verbesserungen) diese Version zum Approval schicken in: https://github.com/DP-3T/documents/tree/master/public_engagement/cartoon 

![shortened_onepage_de](https://user-images.githubusercontent.com/64364916/83165555-fa0ca180-a10d-11ea-8ab6-28118730bf97.png)

**Comment by julizet** [comment]
Am Ende der deutchen Comic-Version im offiziellem GitHUb Repo (siehe Markdown [hier](https://github.com/DP-3T/documents/blob/master/public_engagement/cartoon/de/Comic.md)) steht, dass der Comic Public Domain ist. Nachfolgend wird erläutert, dass man dadurch bereits die Erlaubnis hat den Comic für eigene Apps/Erklärungen zu verwenden und man darüber hinaus die Erlaubnis zur Übersetzung des Comics hat.

Wir bewegen uns hier glücklicherweise innerhalb einer Open-Source-Community, sodass ich kein Problem darin sehe, dass du den Comic angepasst und in einem deutschen OnePager verwandelt hast. Im Gegenteil, das nützt uns sehr.

**Änderungen**
Mir ist aufgefallen, dass du die englische Bebilderung nutzt. Zur Vermeidung von Wort-Bild-Scheren und auch, um wirklich alle Menschen erreichen und konsisten bleiben zu können: kes wäre sinnvoll die deutsche Bebilderung nutzen (die sind alle in dem Repository im Ordner "de").

Ich habe darüber hinaus noch ein paar textliche Anmerkungen zu den einzelnen Bildern, wobei die textlichen Änderungen vor allem auf den original deutschen Comic basieren und etwas konkreter Beleuchten, wie der ganze Kauderwelsch funktioniert:

1. Frame:
Alle 5 Minuten verschickt Alice Smartphone per Bluetooth zufälliges Kauderwelsch an alle Geräte in der Nähe. Jede Nachricht ist ein Unikat.

2. Frame:
Alice sitzt neben Bob. Wenn sie länger als 5 Minuten nebeneinander sitzen, werden ihre Smartphones unverständliche Kauderwelsche austauschen.

3. Frame:
Beide Smartphones merken sich 14 Tage lang die Kauderwelsch-Unikate die sie verschickt und empfangen haben. Private Informationen werden nicht ausgetauscht.

4. Frame:
Alice hat Covid-19 und lädt ihre "WAS ICH SAGTE"-Unikate an eine Datenbank in das Krankenhaus hoch. Dafür bekommt sie einen Einmalschlüssel ihrer Äzrt*in (so wird Spam vermieden)

5. Frame:
Und nochmal: da das Kauderwelsch zufällig ist, werden dem Krankenhaus keine persönlichen Informationen über Alice verraten. Für das Krankenhaus ist es Kauderwelsch...

6. Frame: 
... aber Bob`s Smartphone liest die Listen der Krankenhäuser regelmäßig und prüft, ob es in den letzten 14 Tagen von diesen "Unikaten" gehört hat.

7. Frame: 
[...] schickt er Bob per Nachricht in häusliche Quarantäne.

8. Frame: 
'-

**Vorschlag:**
Wenn der deutsche OnePager unter uns final abgesitmmt ist, als Pull-Request dem offiziellem Repo hinzufügen.

@eagle-seagull

**Comment by eagle-seagull** [comment]
Änderungen wurden vorgenommen:
![shortened_onepage_de#2](https://user-images.githubusercontent.com/64364916/83359544-1feaae00-a37b-11ea-94d8-28858e7f5406.png)

Falls Änderungen am Text erwünscht sind, sind diese nun schnell umsetzbar.

**Comment by julizet** [comment]
Super, vielen Dank für die Anpassungen. Sieht schick aus & wurde so in die Einleitung eingfügt.

Da von den anderen Teamitgliederung kein weiteres Feedback kam schließe ich das Issue.
