### ISSUE TITLE
Letzten Block "App Akzeptanz einer "sicheren" App" überarbeiten

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#59]
# Bounty
Review & resolven der Anmerkungen des letzten Blockes

## Scope

-

## Deliverables

-

## Gain for the project

>Wenn Sie die Punkte drin haben, leite ich den Fragebogen umgehend weiter.
Herzlichst,
Claudia Müller-Birn

## Roles

bounty worker: @username
bounty reviewer: @Erdanf 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Erdnaf** [comment]
@bernd96 ich heb ein Paar Kleine Dinge im GDoc geändert, schau nochmal drüber, dann kann ich das in Limesurvey übertragen

**Comment by bernd96** [comment]
@Erdanf Passt alles soweit, hab die Sachen approved

**Comment by bernd96** [comment]
Ich hab die sachen alle in docs markiert, die sind ja noch nicht in limesurvey

**Comment by Erdnaf** [comment]
sind in limesurvey
