### ISSUE TITLE
Anpassung der Tabellengröße auf der Vergleich-Webseite

### ISSUE THREAD

**Issue by kraleva** [FUB-HCC/20-SWP-CodingOpenness#62]
# Bounty

Die Vergleichstabellen auf der Github-Page sollten aus unserer Sicht (Team Vergleich) breiter gemacht werden.

## Scope

Die Tabellengröße bzgl. Breite sollte angepasst werden, da aus unserer Sicht (Team Vergleich) es einfach viele Informationen gibt und man könnte die Breite besser nutzen. Es gibt auch Dropdownzeilen, die auch mit Hilfe davon besser dargestellt werden können und auch leichter zum Lesen sein können.

## Deliverables

- Breitere Tabelleformatierung auf der Vergleich der Ansätze Pfad von der Github Page

## Gain for the project

- Bessere Veranschauligung
- Übersichtlicher für den Expertenpanel

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by sontungg** [comment]
Hi @kraleva, wir  fetchen die .md files einfach nur, falls ihr Dinge am Aussehen ändern wollt, bitten wir euch einfach die .md files zu ändern.

Gruß
Tung

**Comment by kraleva** [comment]
> Hi @kraleva, wir fetchen die .md files einfach nur, falls ihr Dinge am Aussehen ändern wollt, bitten wir euch einfach die .md files zu ändern.
> 
> Gruß
> Tung

Man könnte mit Hilfe der .md Dateien nicht die Breite der Tabellen verändern, dies wird entweder in den React-Componenten gemacht oder bei der CSS Formatierung der Seite, so wir bitten, dass die Breite irgendwie passend da verändert wird.
