### ISSUE TITLE
Fragebogen

### ISSUE THREAD

**Issue by eagle-seagull** [FUB-HCC/20-SWP-CodingOpenness#7]
*** Team Fragebogen
TODO: Erstellen von Fragen zur potentiellen Nutzung der Corona-Tracing App
TODO: Eruieren, welche Werkzeuge exisieren (Tipp, LIME Survey auf User-Seiten des Fachbereichs)
TODO: Zusammenstellen von Informationen, wie Personen erreicht werden können und wie der Fragebogen verteilt werden kann

**Comment by eagle-seagull** [comment]
*** Team Fragebogen
TODO: Erstellen von Fragen zur potentiellen Nutzung der Corona-Tracing App
 o Gemeint ist, welche Fragen wir den Endnutzern stellen können, um mögliche Hürden für die Nutzung der App zu entdecken
  - Privatsphäre 
  - Datenschutz
  - Grundmotivation der App-Nutzung / Bereitschaft zur Langzeitnutzung
  - Technische Einschränkungen (Batterieverbrauch, OS-Kompatibilität)_
  - Design / leichte Bedienung der App (Tutorial bei Erstnutzung?) <-- schwer Fragen formulierbar
 o Alle Nutzergruppen berücksichtigen (Jugendliche, junge Erwachsene, Erwachsene, alte Erwachsene)
 o Wenn möglich nur einen Fragebogen erstellen

**(Mögliche) Ziele der Fragebogenauswertung:**
- Welche Personengruppen möchten die Corona-App gerne / welche nicht so gerne nutzen?
- Welche Anforderungen werden an die Corona-App gestellt? Was wird vom Können der App erwartet?
- Wie stark wird die Privatsphäre gefühlt eingeschränkt?


[fragebogen11-mai-2020.txt](https://github.com/FUB-HCC/20-SWP-CodingOpenness/files/4611226/fragebogen11-mai-2020.txt)

**Comment by molpremotone** [comment]
TODO: Eruieren, welche Werkzeuge existieren (Tipp, LIME Survey auf User-Seiten des Fachbereichs)

- Brainstorming in einem Dokument, auf das wir alle gleichzeitig zugreifen können, z. B. Overleaf
- ausgearbeitete Fragen in Telegram sammeln
- Guide für LIME Survey verwenden und konfigurieren https://userpage.fu-berlin.de/~rober/blog/2016/02/limesurvey-install-userpage/ (Downloadlink für LIME Survey: https://www.limesurvey.org/stable-release)

**Comment by almohamad-basel** [comment]
TODO: Zusammenstellen von Informationen, wie Personen erreicht werden können und wie der Fragebogen verteilt werden kann.

o Email Verteiler von Uni
o Persönliche Kontakte fragen (WhatsApp, E-Mails, Familien, Freunde)
o Soziale Medien (Twitter, Reddit, Facebook)

**Comment by bernd96** [comment]
TODO:
- Wiki-page erstellen, auf der alle jetzigen Fragen sind. Damit können andere im Modul einfach Feedback geben.
Done, siehe [Fragebogen](https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/Fragebogen)

TODO:
Bis nächste Woche: 3-4 Fragebögen erstellen je nach Wissensstand vom Beantwortenden, die jeweils die Motivation zur App-Nutzung abfragen.


TODO:
    Klären: Soll getrennt werden zwischen Teilnehmern, die die App nutzen/nicht nutzen wollen? Muss / sollte man dafür einen extra Fragebogen erstellen?

TODO:
Typeform.com anschauen. Sind abzweigende Fragebögen möglich? Wenn nicht, separate Fragebögen erstellen.

**Comment by julizet** [comment]
**Zum Thema Typeform:**
Es gibt verschiedene pricing models, wobei das **free model** mir nicht wirklich geeignet scheint, da:
- max. 3 verschiedene Umfragen erstellt werden können
- man pro Umfrage max. 10 Fragen verwenden darf
- max. 100 Rückmeldung / Monat möglich sind (danach ist die URL zwar noch aktuell, aber man kann an der Umfrage nicht mehr teilnehmen)

[Hier zu lesen](https://www.typeform.com/pricing/)  (unten links)

Daher richtet sich meine Frage an @clmb : Inwiefern wäre es möglich einen Typeform-Account der FUB nutzen?

Gerne kann ich die Fragebögen in TF aufsetzen, wenn wir uns für das Tool entscheiden.

**Comment by bernd96** [comment]
ToDo bis Montag
- [ ] Fertig strukturierter Fragebogen
- [ ] Pro Fragencluster ein Ziel formulieren, damit man neue Fragen in diesem Cluster schaffen kann oder alte verwerfen, wenn sie diesem Zweck nicht dienen
- [ ] Reihenfolge der Fragen
  * Wie erzeugen wir einen guten "Fluss"
  * Wie verhindern wir ein "Abdriften" der Benutzer (+ Kontrollfragen, ob der Nutzer noch aufmerksam ist, Fortschrittsbalken)
  * Können wir bestimmte Effekte durch die Reihenfolge hervorrufen/vermeiden
* folgende Informationen beschaffen bis Freitag
  - [ ] Wann und wo treffen wir uns am Freitag?
  - [ ] Qualitativ vs Quantitativ - wie viele Leute werden befragt?

**Comment by eagle-seagull** [comment]
> **Zum Thema Typeform:**
> Es gibt verschiedene pricing models, wobei das **free model** mir nicht wirklich geeignet scheint, da:
> 
> * max. 3 verschiedene Umfragen erstellt werden können
> * man pro Umfrage max. 10 Fragen verwenden darf
> * max. 100 Rückmeldung / Monat möglich sind (danach ist die URL zwar noch aktuell, aber man kann an der Umfrage nicht mehr teilnehmen)
> 
> [Hier zu lesen](https://www.typeform.com/pricing/) (unten links)
> 
> Daher richtet sich meine Frage an @clmb : Inwiefern wäre es möglich einen Typeform-Account der FUB nutzen?
> 
> Gerne kann ich die Fragebögen in TF aufsetzen, wenn wir uns für das Tool entscheiden.

@julizet Hey Julia, ich habe eine e-Mail an Fr. Müller-Birn geschickt, in der ich den Zugang zu Typeform und alternativ zu "Lime Survey"-Experten abgefragt habe. Ich gebe Bescheid, wenn ich dazu Neuigkeiten habe.

**Comment by clmb** [comment]
Hallo. Ich habe mich getäuscht. Es gibt an der FU nur: https://votingo.cedis.fu-berlin.de/ Ich würde aber darum bitten, TypeForm nur dann zu nutzen, wenn klar ist, was mit den Nutzerdaten passiert. Ich bin eher dafür, hier mit einer weniger fancy Lösung zu arbeiten, damit aber sicherzustellen, dass man die Kontrollen über die Daten behält. Wir haben uns zumeist LimeSurvey auf einer FU Informatik User Page installiert und genutzt. Sieht zwar weniger professionell aus, aber ist dafür besser kontrollierbar.

**Comment by bernd96** [comment]
Ich schließe dieses Issue, weil es zur Problematik des Werkzeugs etwas eignes gibt.
