### ISSUE TITLE
Übertragen der Fragen nach LimeSurvey

### ISSUE THREAD

**Issue by bernd96** [FUB-HCC/20-SWP-CodingOpenness#71]
# Bounty
Übertragen der Fragen nach LimeSurvey
## Scope

- 

## Deliverables

- Fertige Umfrage

## Gain for the project

- Umfrage ist fertig und kann ausgeschickt werden

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by eagle-seagull** [comment]
Ich habe die Fragen in lime survey übertragen und im Google-Doc Anmerkungen an Stellen gemacht, die nicht so komplett übernommen werden konnten.
Der Fragebogen heißt "Akzeptanz einer Corona Tracing-App" in lime survey.


Probleme:
- Es gibt keine "Sonstiges"-Felder in Arrays
- Man kann keinen Text unter Arrays anzeigen lassen, nur unter der Frage direkt
- Bei "Sonstiges"-Antworten kann der Text "Sonstiges" nicht geändert werden, so kann man z.B. nicht "Andere App, und zwar" schreiben

Noch fehlt die Logik, dass man nur bei bestimmten Fragen bestimmte Antworten sieht.

**Comment by Erdnaf** [comment]
Ich hab mal drüber geschaut, hier die Dinge die ich Inhaltlich angepasst habe: 
- Habe bei der Mehrfachauswahl immer die Maximalzahl der Antworten erhöht
- Habe die Logik soweit sie fest steht steht eingeführt (z.B. die Dinge aus #102 noch nicht)
- Quelle, die ich für die Logik verwendet habe https://manual.limesurvey.org/Setting_conditions/en#Overview_of_Conditions_in_LimeSurvey

**Comment by julizet** [comment]
Review begonnen. Nachfolgend, alle Änderungen/Anpassungen/Erweiterungen:
1. Einleitung hinzugefügt
<img width="1256" alt="Bildschirmfoto 2020-06-06 um 12 54 33" src="https://user-images.githubusercontent.com/52455010/83942570-e12e7b00-a7f4-11ea-82c0-fdc6f08588e7.png">

**Comment by julizet** [comment]
- Aktivierung der Funktion "Setze Cookie um wiederholte Teilnahme auszuschließen"
- Aktivierung der Funktion "Anonymisierte Antworten"

**Comment by julizet** [comment]
Einleitung gemäß Fragebogen (GDoc) angepasst
--> Comic eingefügt
--> Verständnisfragen in Blöcke (insgesamt 3) eingeteilt
--> Frage ohne Antwort ("Bitte beantworten sie die Fragen, als hätten Sie ein Smartphone") gelöscht

**Comment by julizet** [comment]
Fragen von @bernd96  bezüglich der Bedenken hinzugefügt + Struktur im Block "Konkrete Fragen zur Benutzung [...]" angepasst

@Erdanf 
@eagle-seagull 
Bitte um Review :)

**Comment by Erdnaf** [comment]
Bin beim Review:

Sachen, die ich geändert habe:

> --> Frage ohne Antwort ("Bitte beantworten sie die Fragen, als hätten Sie ein Smartphone") gelöscht

Dieser Text existiert nach Strukturgraph, wenn man kein Spartphone besitzt und wird auch nur dann angezeigt

> Bei "Sonstiges"-Antworten kann der Text "Sonstiges" nicht geändert werden, so kann man z.B. nicht "Andere App, und zwar" schreiben

Doch das geht, es ist unter Display > label for Other Option. 
Habe es bei der Fage nach Bezahlmethoden und dem Geschlecht geändert

Hab ansonsten nochmal die Verzweigungen aktualisiert

**Comment by Erdnaf** [comment]
ich würde vorschlagen das Issue erstmal zu schließen, oder wollen wir warten, bis #112 und #102 abgeschloseen sind?

Wir könnten dann auch ein neues Issue erstellen, wenn diese Dinge abgeschlossen sind
