### ISSUE TITLE
Theme von https://pages.github.com/themes/ in die Webseite integrieren   https://github.com/collections/github-pages-examples

### ISSUE THREAD

**Issue by tratond01** [FUB-HCC/20-SWP-CodingOpenness#74]
# Bounty

## Scope

- Integrate Themes into website

## Deliverables

- Integration of pre-exisiting themes, update code

## Gain for the project

- new appearance for the website

## Roles

bounty worker: @username
bounty reviewer: @username

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by omerhod** [comment]
we can't use any gh page template because we use react and not jekyll.
