### ISSUE TITLE
Sammeln der wichtigsten User Stories und Erstellen von zugehörigen Diagrammen

### ISSUE THREAD

**Issue by JuliusBro** [FUB-HCC/20-SWP-CodingOpenness#75]
# Bounty
Die wichtigsten User Stories aus der offiziellen Dokumentation sollten auch bei uns gesammelt sein, am Besten mit zugehörigen Diagrammen, die den Ablauf verdeutlichen.
## Scope

- Entweder die user Stories, wenn wirklich wichtig, einfach übernehmen, ansonstens eventuell zusammenfassen

## Deliverables

- Portierte wichtige User Stories mit zugehörigem Diagramm (max. 5)

## Gain for the project

- Vorbereitung für tatsächliches Programmieren

## Roles

bounty worker: @dennisn00 
bounty reviewer: @JohBrose

**Comment by dennisn00** [comment]
Ich habe die Wiki-Seite erstellt und einige Diagramme/Erläuterungen eingefügt. Die restlichen User-Stories folgen morgen.
https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/User-Stories-f%C3%BCr-die-offizielle-Corona-Warnapp

**Comment by dennisn00** [comment]
Bitte reviewen @JohBrose

**Comment by dennisn00** [comment]
Danke für das Review @JohBrose.
Damit schließe ich das Issue.
Das Ergebnis ist hier zu finden: https://github.com/FUB-HCC/20-SWP-CodingOpenness/wiki/User-Stories-f%C3%BCr-die-offizielle-Corona-Warnapp
