### ISSUE TITLE
Super Review - Fragebogen

### ISSUE THREAD

**Issue by Erdnaf** [FUB-HCC/20-SWP-CodingOpenness#79]
# Bounty

Der Fragebogen mit dem Strukturgraphen wird auf Konsitenz geprüft 

## Scope

- Prüfung des Google Docs

## Deliverables

Google Doc

## Gain for the project

- Konsitenz

## Roles

bounty worker: @Erdanf 
bounty reviewer: @bernd96 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Erdnaf** [comment]
Super Review ist soweit durch.
Ich habe vor allem das Google Dokument an die Fragenstruktur angepasst, hauptsächlich die Reihenfolge geändert, und ein paar kleinere Änderungen gemacht. 
Wenn euch noch was auffällt, schreibt das hier rein.
Als Review am besten die Vorgeschlagenen Änderungen im Google Doc annehmen/kommentieren

**Comment by bernd96** [comment]
Sieht gut aus.
 - Hab alle Vorschläge bis auf 2 bestätigt, ich hab nen Kommentar geschrieben warum nicht (sind Kleinigkeiten)
 - Ich hab noch ein paar Typos ("Sie" vs "sie") korrigiert

**Comment by Erdnaf** [comment]
@bernd96 Hab auf deine Sachen geantwortet, schau nochmal drüber, dann können wir das Issue schleißen

**Comment by julizet** [comment]
habe soeben auch noch ein paar Kommentare "resolved" bzw. kommtentiert.

Die Antwortmöglichkeiten bei der Frage "Welche Bedenken hätten Sie bei der Nutzung einer solchen Corona App?" sollten wir m.E.n. minimieren.
