### ISSUE TITLE
Formulierung – Kontrollfragen Einleitung 

### ISSUE THREAD

**Issue by julizet** [FUB-HCC/20-SWP-CodingOpenness#80]
# Bounty
Die Einleitung erläutert die Funktionsweise einer Corona-Tracing-App. Damit überprüft werden kann, ob Teilnehmer*innen diese Funktionsweise auch wirklich verstanden haben, soll die Einleitung durch Kontrollfragen ergänzt werden.

## Scope
- Schweizer Umfrage als Beispiel reviewen (evtl. noch andere Umfrage)
- Kontrollfragen formulieren
- Kontrollfragen an entsprechender Stelle einbauen

## Deliverables
- Einleitung mit Kontrollfragen

## Gain for the project
- Überprüfung, ob Teilnehmer*innen die App verstehen

## Roles

bounty worker: @julizet 
bounty reviewer: @eagle-seagull 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by julizet** [comment]
Ich habe die Anpassung der Einleitung direkt in unserem **working doc auf Google Drive** vorgenommen.

**Übersicht der DREI Verständnisfragen**
Um sicher zu stellen, dass alle Umfrage-Teilnehmer*innen die Funktionweise verstanden haben, werden folgende Kontrollfragen gestellt:

**Verständnisfrage: Welche Einstellungen müssen Sie auf Ihrem Smartphone erlabuen, damit die App funktioniert? (Mehrfachauswahl möglich)**
* einen Account erstellen
* Zugriff auf meine Fotos erlauben
* Zugriff auf meine Kontakte erlauben
* Bluetooth aktivieren oder aktiviert lassen
* Zugriff auf meinen aktuellen Standort erlauben


**Verständnisfrage: Was müssen sie tun, wenn bei Ihnen eine Covid-19-Infektion diagnostiziert wurde? (KEINE Mehrfachauswahl möglich)**
* Nichts, mein Arzt/meine Ärztin sendet die Diagnose an alle anderen App-Nutzer*innen
* Nichts, die App informiert nach der Diagnose automatisch möglicherweise infizierte Personen 
* Zunächst die Diagnose in der App melden, um möglicherweise infizierte Personen automatisch zu informieren
* mein Handy ausschalten

**Verständnisfrage: Was würde die App tun, wenn bei jemandem, zu dem Sie engen Kontakt hatten, das Coronavirus diagnostiziert wurde? (KEIN Mehrfachauswahl möglich)**
* Mich zur stärkeren Reduzierung meiner Kontakte auffordern
* Mir eine "Alles Ok" Nachricht anzeigen
* Mir den Namen der erkrankten Person mitteilen
* Mich in Selbstquarantäne schicken
* Mich bei den Gesundheitsämtern melden

**Comment by julizet** [comment]
Zudem habe ich eine weitere, gänzlich neue Frage zum Doce hinzugefügt, weil diese bis dato noch gefehlt hat, laut Strukturgraph allerdings logisch und notwendig ist.


**Begründen Sie bitte Ihre vorherige Antwort: warum würde Sie eine solche Corona-App nicht installieren wollen? (Mehrfachauswahl möglich)**
* ich sehe die App als Vorwand für eine stärkere Überwachung durch den Staat
* ich finde den Nutzen zur Eindämmung der Pandemie nicht überzeugend
* ich habe Bedenken, dass die App nicht richtig funktioniert (falscher Alarm)
* ich habe die Befürchtung, dass mein Smartphon leichter gehackt werden kann
* ich habe Angst, dass andere erfahren, dass ich mich angesteckt habe
* ich wäre mit der Benutzung der App überfordert
* Sonstiges, und zwar: <FREITEXT>

**Comment by julizet** [comment]
Last but not least: erster Fragenkomplex "Fragen zum Umgang mit Smartphones und Apps" überarbeitet und Comments von CMB resolved.

Bitte um Review: @eagle-seagull

**Comment by bernd96** [comment]
> Zudem habe ich eine weitere, gänzlich neue Frage zum Doce hinzugefügt, weil diese bis dato noch gefehlt hat, laut Strukturgraph allerdings logisch und notwendig ist.
> 
> **Begründen Sie bitte Ihre vorherige Antwort: warum würde Sie eine solche Corona-App nicht installieren wollen? (Mehrfachauswahl möglich)**
> 
> * ich sehe die App als Vorwand für eine stärkere Überwachung durch den Staat
> * ich finde den Nutzen zur Eindämmung der Pandemie nicht überzeugend
> * ich habe Bedenken, dass die App nicht richtig funktioniert (falscher Alarm)
> * ich habe die Befürchtung, dass mein Smartphon leichter gehackt werden kann
> * ich habe Angst, dass andere erfahren, dass ich mich angesteckt habe
> * ich wäre mit der Benutzung der App überfordert
> * Sonstiges, und zwar:

Ich werde demnächst die Frage mit den erkenntnissen der schweizer umfrage ergänzen

**Comment by julizet** [comment]
> > Zudem habe ich eine weitere, gänzlich neue Frage zum Doce hinzugefügt, weil diese bis dato noch gefehlt hat, laut Strukturgraph allerdings logisch und notwendig ist.
> > **Begründen Sie bitte Ihre vorherige Antwort: warum würde Sie eine solche Corona-App nicht installieren wollen? (Mehrfachauswahl möglich)**
> > 
> > * ich sehe die App als Vorwand für eine stärkere Überwachung durch den Staat
> > * ich finde den Nutzen zur Eindämmung der Pandemie nicht überzeugend
> > * ich habe Bedenken, dass die App nicht richtig funktioniert (falscher Alarm)
> > * ich habe die Befürchtung, dass mein Smartphon leichter gehackt werden kann
> > * ich habe Angst, dass andere erfahren, dass ich mich angesteckt habe
> > * ich wäre mit der Benutzung der App überfordert
> > * Sonstiges, und zwar:
> 
> Ich werde demnächst die Frage mit den erkenntnissen der schweizer umfrage ergänzen

die top drei Gründe der schweizer Umfrage sind schon drin (absteigend: Überwachung / falscher Alarm / Hacking) aber wenn du magst, kannst du gerne noch ein paar andere hinzufügen.

**Comment by eagle-seagull** [comment]
Review:
- Kleinere Rechtschreibfehler angepasst

Im Google-Doc die Anmerkungen akzeptiert bzw. Kommentiert:
- Begründen Sie bitte Ihre vorherige Antwort: warum würde Sie eine solche Corona-App nicht installieren wollen? (Mehrfachauswahl möglich)
    Kommentar: Klingt die Frage 'netter', wenn man nur "Warum würden Sie eine solche...." stellt? Der erste Part klingt wie ein "rechtfertigen Sie sich".

- Text zu Zweitkontakten wurde von 2 Personen bearbeitet, sodass keine richtige Satzstruktur mehr vorhanden war - ich habe es vorerst so zusammengefasst (und als Änderungsvorschlag im Google-Doc eingefügt.):
    Sie werden auch benachrichtigt, wenn sie mit einer Person Kontakt hatten, die wiederum direkten 
    Kontakt mit einer infizierten Person hatte.
    Beispiel: Wenn sie mit einer Person – “Bob” – Kontakt hatten, welche wiederum direkten Kontakt 
    zu einer infizierten Person – “Alice – hatte, werden Sie benachrichtigt, obwohl Sie keinen direkten 
    Kontakt zur infizierten Person “Alice” hatten.

Sonst sieht's gut aus!

**Comment by bernd96** [comment]
> Zudem habe ich eine weitere, gänzlich neue Frage zum Doce hinzugefügt, weil diese bis dato noch gefehlt hat, laut Strukturgraph allerdings logisch und notwendig ist.
> 
> **Begründen Sie bitte Ihre vorherige Antwort: warum würde Sie eine solche Corona-App nicht installieren wollen? (Mehrfachauswahl möglich)**
> 
> * ich sehe die App als Vorwand für eine stärkere Überwachung durch den Staat
> * ich finde den Nutzen zur Eindämmung der Pandemie nicht überzeugend
> * ich habe Bedenken, dass die App nicht richtig funktioniert (falscher Alarm)
> * ich habe die Befürchtung, dass mein Smartphon leichter gehackt werden kann
> * ich habe Angst, dass andere erfahren, dass ich mich angesteckt habe
> * ich wäre mit der Benutzung der App überfordert
> * Sonstiges, und zwar:

@julizet Hast du die Auswahlantworten aus der Schweizer umfrage genommen?

**Comment by julizet** [comment]
Bis auf die Frage "Welche Bedenken hätten Sie bei der Nutzung einer solchen Corona App?" ist die Einleitung fertig + auch der deutsche (überarbeitete) Comic wurde eingefügt.

Daher schließe ich das Issue.

Danke für euer Review @eagle-seagull & @bernd96
