### ISSUE TITLE
Feedback on Website: https://fub-hcc.github.io/20-SWP-CodingOpenness/

### ISSUE THREAD

**Issue by aschle** [FUB-HCC/20-SWP-CodingOpenness#81]
- Logo - if you ever need to use one please use the following:
![HCC-NewLogo-Image-Brand@2](https://user-images.githubusercontent.com/883797/83129845-b26e2180-a0dd-11ea-9455-9bac04a11a1f.png)

- What is the thing next to the logo?
![image](https://user-images.githubusercontent.com/883797/83129961-dd587580-a0dd-11ea-8858-720c29a98fff.png)
Look maybe at https://material.io/design for inspiration or 

- Navigation: **Ansätze** --> What for?
- Looking at the page the first time I have no clue what this is about, okay I have to read the lengthy text, but as a first time visitor of the website I do not feel very motivated to read a lot of text 👀
- The text in the box is hard to read cause it stretches all along from left to write, if you use Bootstrap, you can use columns.
- Mehr Informationen F(?)inden Sie **hier** - "Hier" is generally a very bad idea. People have to read the context to find out WHAT exactly HIER means http://www.uxforthemasses.com/click-here/
- When I click on "HIER" I can not use the browser BACK button, sorry this is like to very nice 💣 How do I get back? I thought my Chrome-browser crashed! If you use Jekyll (which comes with GitHub pages out of the box) this should be working out of the box anyway, maybe change the config.md/json.
- Please make the navigation sticky, if I click on **Ansätze** and then e.g. `DP-3T` then I don't know where I am, the navigation is gone.
- Generally a note on frames: To make something be perceived as a group it is better to use a background color and not a frame: https://lawsofux.com/law-of-common-region.html
- List of criteriums and features: The pattern I know or would expect for tables and then items meeting that criterium or not I would expect ✔️ s. E.g. like here: https://www.grammarly.com/plans?utm_source=upHook&app_type=app&page=free&utm_campaign=editorMenu&utm_medium=internal (just an idea)
- Use PNGs so you have a transparent background
![image](https://user-images.githubusercontent.com/883797/83131647-75eff500-a0e0-11ea-83a3-f9b2a8a8628b.png)
- Please scroll through Bootstrap to get an idea of User Interfaces, e.g. When to used collapsible, when to use tooltips, when to use 
- I am struggling with the tables, all those collapsible, and the text-center this is very hard to read for me. Why did you choose a table? What is the information the reader should learn from the table? What is the goal of that table? What is the most important information for the reader?
- Über uns: remove old HCC logo, please.
- Über uns: text which stretches all along the page is hard to read. Check out https://baymard.com/blog/line-length-readability to read more on that topic.
- Links need to be clickable not just the icon.

I did not intend to sound rude, I just had no time to go through, what I have written again.

**Comment by aschle** [comment]
I had not time to create single tickets.

**Comment by clmb** [comment]
Bitte erstellen sie einzelne Tickets aus diesem Issue.

**Comment by omerhod** [comment]
@aschle thanks a lot for your constructive feedback, it is clear that you invested a good amount of time in it.
We'll take the time to create stand alone tickets for each bullet point.
