### ISSUE TITLE
Review Strurkturgraph für den Fragebogen

### ISSUE THREAD

**Issue by gancia-kiss** [FUB-HCC/20-SWP-CodingOpenness#82]
# Bounty
Review von der Erstellte Strurkturgraph für den Fragebogen: 
https://drive.google.com/file/d/1Pn0bv9PAgVtEH8uZo8vj0nBfoWobGV7Y/view?usp=sharing
## Scope
ToDo: 
-Graph durchgehen und Anmerkungen und Modifikation erstellen.

## Deliverables
in Draw.io
-

## Gain for the project

-

## Roles

bounty worker: @gancia-kiss 

## Issue creation checklist

- [x] I have attached one of the team labels `Fragebogen`, `Technik`, `Projektwebseite`, `Vergleich`, `Organisation` to this bounty
- [x] I have attached one of the priority labels `Blocker`, `High`, `Medium`, `Low` to this bounty
- [x] I have attached one of the `size-` labels to this bounty
- [x] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by gancia-kiss** [comment]
Strukturgraph Review ist jetzt Fertig. Die Rote linien sind die Linien die nach meine Meinung nach nicht existieren sollen. Die Grüne Linien sind meine Korrektur Linien oder markiert der Korrektur Bereiche.

Reviewgraph-Link: https://drive.google.com/file/d/1gbtyFWdDOuFY_hVJB6zqVpj2ZUvXV4ph/view?usp=sharing

**Comment by linuxhelf** [comment]
danke fürs Review, wir haben den Strukturgraph etwas überarbeitet
