### ISSUE TITLE
Rechte fehlen: Wiki pages erstellen & bearbeiten, Berechtigung: Labels hinzufügen

### ISSUE THREAD

**Issue by eagle-seagull** [FUB-HCC/20-SWP-CodingOpenness#9]
# Bounty / Aufgabe
XXS
Meinem Account fehlt die Berechtigung, Wiki-Pages zu erstellen und zu bearbeiten (Ist aufgefallen, als ich eine von einem anderen Nutzer erstellte Wiki-Seite "Fragebogen" bearbeiten wollte.)
Beim Erstellen dieses Issues ist aufgefallen, dass ich keine Label hinzufügen kann.

## Scope / Umfang

- Jeder Nutzer, der noch fehlende Rechte hat, soll diese erhalten.
- @Clearwood und @adrianapintod sollten vielleicht Adminrechte erhalten, damit diese administrative Aufgaben übernehmen können.

## Deliverables

- Rechte zum Erstellen von Wiki-Pages erhalten
- Rechte zum Bearbeiten von Wiki-Pages erhalten
- Rechte zum Labels in Issues hinzufügen erhalten

## Gain for the project / Nutzen für das Projekt

- Man kann die Aufgaben im Wiki bearbeiten. Man kann seinen Wissensschatz selbst hinzufügen.

## Roles / Rollen

bounty worker: @username
bounty reviewer: @username

## Gardener checklist

- [ ] I have attached one of the `size-`  @labels to this bounty
- [ ] I have added this bounty to bounty board here https://github.com/FUB-HCC/20-SWP-CodingOpenness/projects/1

**Comment by Clearwood** [comment]
Du musst die Einladung erst annehmen: https://github.com/FUB-HCC/20-SWP-CodingOpenness/invitations

**Comment by eagle-seagull** [comment]
Ah, danke - meine Einladung ist leider abgelaufen, kann ich eine neue bekommen? =)

**Comment by adrianapintod** [comment]
@eagle-seagull I just sent you the invitation

**Comment by eagle-seagull** [comment]
Entschuldigt, dass ich dieses Issue wieder öffne - ich habe den Link angeklickt und mir wurde bestätigt, dass ich die Einladung angenommen habe, kann allerdings keine Änderung meiner Rechte feststellen. Ich habe gehört, dass ich noch manuell freigeschaltet werden muss. Könnt ihr mir dabei nochmal helfen?
Danke =)

**Comment by Clearwood** [comment]
@eagle-seagull du solltest jetzt alle Rechte haben :)
